<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AccountSettingSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('account_setting')->insert([
                ['id' => 3, 'voucher_type_id' => 1, 'department_id' => 0, 'voucher_name' => 'PURCHASE INVOICE', 'prefix' => '', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 16, 'cr_account_master_id' => 0, 'status' => 0, 'created_at' => '2018-09-11 09:28:11', 'created_by' => 0, 'modified_at' => '2026-02-03 14:24:02', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => '', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 13, 'voucher_type_id' => 3, 'department_id' => 1, 'voucher_name' => 'CAR WASH ', 'prefix' => '', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 0, 'cr_account_master_id' => 64, 'status' => 0, 'created_at' => '2018-11-26 14:37:15', 'created_by' => 0, 'modified_at' => '2026-01-27 23:20:05', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => '', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 14, 'voucher_type_id' => 3, 'department_id' => 2, 'voucher_name' => 'TYRE SALES', 'prefix' => '', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 0, 'cr_account_master_id' => 65, 'status' => 0, 'created_at' => '2018-11-26 14:37:47', 'created_by' => 0, 'modified_at' => '2026-01-27 23:20:05', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => '', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 23, 'voucher_type_id' => 15, 'department_id' => 0, 'voucher_name' => 'MANUFACTURE', 'prefix' => '', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 5633, 'cr_account_master_id' => 5682, 'status' => 1, 'created_at' => '2020-09-17 11:08:00', 'created_by' => 0, 'modified_at' => '2024-09-09 15:02:22', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => '', 'dr_account_master_id_to' => 5682, 'cr_account_master_id_to' => 5639],
                ['id' => 53, 'voucher_type_id' => 24, 'department_id' => 0, 'voucher_name' => 'SALES SPLIT', 'prefix' => '', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 0, 'cr_account_master_id' => 0, 'status' => 1, 'created_at' => '2021-04-15 08:04:03', 'created_by' => 0, 'modified_at' => '2025-12-02 17:45:36', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => '', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 57, 'voucher_type_id' => 25, 'department_id' => 0, 'voucher_name' => 'PURCHASE RENTAL', 'prefix' => '', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 55, 'cr_account_master_id' => 0, 'status' => 1, 'created_at' => '2022-10-07 22:15:33', 'created_by' => 0, 'modified_at' => '0000-00-00 00:00:00', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => '', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 58, 'voucher_type_id' => 26, 'department_id' => 0, 'voucher_name' => 'RENTAL SALES', 'prefix' => '', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 0, 'cr_account_master_id' => 15, 'status' => 1, 'created_at' => '2022-10-10 09:36:40', 'created_by' => 0, 'modified_at' => '0000-00-00 00:00:00', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => '', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 68, 'voucher_type_id' => 3, 'department_id' => 1, 'voucher_name' => 'SALES - CREDIT', 'prefix' => '', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 0, 'cr_account_master_id' => 5980, 'status' => 1, 'created_at' => '2024-06-14 10:57:37', 'created_by' => 0, 'modified_at' => '2026-01-27 23:20:05', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => '', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 69, 'voucher_type_id' => 3, 'department_id' => 1, 'voucher_name' => 'SALES - CASH', 'prefix' => '', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 2762, 'cr_account_master_id' => 15, 'status' => 1, 'created_at' => '2024-06-14 10:58:11', 'created_by' => 0, 'modified_at' => '2026-01-27 23:20:05', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 1, 'default_account_id' => 2762, 'description' => '', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 70, 'voucher_type_id' => 1, 'department_id' => 0, 'voucher_name' => 'PURCHASE - IMPORT', 'prefix' => 'PI', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 5633, 'cr_account_master_id' => 0, 'status' => 1, 'created_at' => '2024-06-14 10:58:43', 'created_by' => 0, 'modified_at' => '2026-02-03 14:24:02', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => '', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 71, 'voucher_type_id' => 1, 'department_id' => 0, 'voucher_name' => 'PURCHASE - LOCAL', 'prefix' => 'PI', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 5633, 'cr_account_master_id' => 0, 'status' => 1, 'created_at' => '2024-06-14 10:59:15', 'created_by' => 0, 'modified_at' => '2026-02-03 14:24:02', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => '', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 72, 'voucher_type_id' => 9, 'department_id' => 1, 'voucher_name' => 'RECEIPT VOUCHER', 'prefix' => null, 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 0, 'cr_account_master_id' => 0, 'status' => 1, 'created_at' => '2024-06-14 10:59:46', 'created_by' => 0, 'modified_at' => '2026-02-05 05:42:18', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 2762, 'bank_account_id' => 5451, 'pdc_account_id' => 2748, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => null, 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 73, 'voucher_type_id' => 10, 'department_id' => 1, 'voucher_name' => 'PAYMENT VOUCHER', 'prefix' => 'PV', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 0, 'cr_account_master_id' => 0, 'status' => 1, 'created_at' => '2024-06-14 11:00:20', 'created_by' => 0, 'modified_at' => '2026-02-05 07:12:13', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 2762, 'bank_account_id' => 5451, 'pdc_account_id' => 2751, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => null, 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 74, 'voucher_type_id' => 23, 'department_id' => 0, 'voucher_name' => 'PURCHASE - SPLIT', 'prefix' => '', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 0, 'cr_account_master_id' => 0, 'status' => 1, 'created_at' => '2024-06-14 11:01:02', 'created_by' => 0, 'modified_at' => '2025-12-02 17:38:48', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => '', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 75, 'voucher_type_id' => 13, 'department_id' => 0, 'voucher_name' => 'GOODS ISSUE NOTE', 'prefix' => '', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 5635, 'cr_account_master_id' => 5633, 'status' => 1, 'created_at' => '2024-06-14 11:03:11', 'created_by' => 0, 'modified_at' => '2024-07-04 14:25:37', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => '', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 76, 'voucher_type_id' => 2, 'department_id' => 0, 'voucher_name' => 'PURCHASE - RETURN', 'prefix' => '', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 0, 'cr_account_master_id' => 5633, 'status' => 1, 'created_at' => '2024-06-14 11:03:42', 'created_by' => 0, 'modified_at' => '2026-02-03 02:29:26', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => '', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 77, 'voucher_type_id' => 4, 'department_id' => 1, 'voucher_name' => 'SALES - RETURN', 'prefix' => '', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 15, 'cr_account_master_id' => 0, 'status' => 1, 'created_at' => '2024-06-14 11:06:52', 'created_by' => 0, 'modified_at' => '2026-01-31 11:52:01', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => '', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 78, 'voucher_type_id' => 16, 'department_id' => 1, 'voucher_name' => 'Journal Voucher', 'prefix' => null, 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => null, 'cr_account_master_id' => null, 'status' => 1, 'created_at' => '2024-07-06 07:43:48', 'created_by' => 0, 'modified_at' => '2026-02-05 05:21:32', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => null, 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 79, 'voucher_type_id' => 28, 'department_id' => 1, 'voucher_name' => 'Manual Journal', 'prefix' => null, 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => null, 'cr_account_master_id' => null, 'status' => 1, 'created_at' => '2024-07-06 08:51:49', 'created_by' => 0, 'modified_at' => '2026-02-05 05:19:14', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => 'MANUAL JOURNAL', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 80, 'voucher_type_id' => 21, 'department_id' => 0, 'voucher_name' => 'Transfer - In', 'prefix' => '', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 5633, 'cr_account_master_id' => 5640, 'status' => 1, 'created_at' => '2024-07-14 19:00:04', 'created_by' => 0, 'modified_at' => '2024-07-14 19:01:19', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => '', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 81, 'voucher_type_id' => 22, 'department_id' => 0, 'voucher_name' => 'Transfer - Out', 'prefix' => '', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 5641, 'cr_account_master_id' => 5633, 'status' => 1, 'created_at' => '2024-07-14 19:00:58', 'created_by' => 0, 'modified_at' => '2024-07-14 19:01:43', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => '', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 82, 'voucher_type_id' => 14, 'department_id' => 0, 'voucher_name' => 'GOODS RETURN', 'prefix' => '', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 5633, 'cr_account_master_id' => 5635, 'status' => 1, 'created_at' => '2024-07-18 10:41:11', 'created_by' => 0, 'modified_at' => '2024-07-18 10:42:10', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => '', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 83, 'voucher_type_id' => 20, 'department_id' => 1, 'voucher_name' => 'Petty Cash Voucher', 'prefix' => null, 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => null, 'cr_account_master_id' => 2762, 'status' => 1, 'created_at' => '2024-10-09 15:10:53', 'created_by' => 0, 'modified_at' => '2026-02-05 05:26:27', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => null, 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 84, 'voucher_type_id' => 18, 'department_id' => 0, 'voucher_name' => 'PDCR Debit Account', 'prefix' => '', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 5451, 'cr_account_master_id' => 2748, 'status' => 1, 'created_at' => '2024-10-10 13:06:48', 'created_by' => 0, 'modified_at' => '2024-11-19 15:33:07', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => '', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 85, 'voucher_type_id' => 19, 'department_id' => 0, 'voucher_name' => 'PDCI  Credit Account', 'prefix' => '', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 2751, 'cr_account_master_id' => 5451, 'status' => 1, 'created_at' => '2024-10-10 16:22:31', 'created_by' => 0, 'modified_at' => '2024-11-19 15:32:51', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => '', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 86, 'voucher_type_id' => 5, 'department_id' => 0, 'voucher_name' => 'Purchase - Non Stock', 'prefix' => '', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 0, 'cr_account_master_id' => 0, 'status' => 1, 'created_at' => '2024-10-19 18:36:34', 'created_by' => 0, 'modified_at' => '0000-00-00 00:00:00', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => '', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 87, 'voucher_type_id' => 6, 'department_id' => 0, 'voucher_name' => 'Sales - Non Stock', 'prefix' => '', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 0, 'cr_account_master_id' => 0, 'status' => 1, 'created_at' => '2024-10-19 18:37:00', 'created_by' => 0, 'modified_at' => '2026-01-22 07:56:23', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => '', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 88, 'voucher_type_id' => 27, 'department_id' => 0, 'voucher_name' => 'Contra Voucher', 'prefix' => '', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 0, 'cr_account_master_id' => 0, 'status' => 1, 'created_at' => '2025-02-20 18:43:23', 'created_by' => 0, 'modified_at' => '2025-04-04 19:18:42', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 2762, 'bank_account_id' => 5753, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => '', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 89, 'voucher_type_id' => 27, 'department_id' => 0, 'voucher_name' => 'C2', 'prefix' => '', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 0, 'cr_account_master_id' => 0, 'status' => 1, 'created_at' => '2025-04-03 14:33:58', 'created_by' => 0, 'modified_at' => '2025-04-03 15:34:09', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 2762, 'bank_account_id' => 5674, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => '', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 90, 'voucher_type_id' => 29, 'department_id' => 0, 'voucher_name' => 'SALES SPLIT RETURN', 'prefix' => '', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 0, 'cr_account_master_id' => 0, 'status' => 1, 'created_at' => '2025-05-08 13:56:19', 'created_by' => 0, 'modified_at' => '2025-05-15 09:35:42', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => '', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 91, 'voucher_type_id' => 30, 'department_id' => 0, 'voucher_name' => 'PURCHASE SPLIT RETURN', 'prefix' => '', 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 0, 'cr_account_master_id' => 0, 'status' => 1, 'created_at' => '2025-05-14 23:30:05', 'created_by' => 0, 'modified_at' => '0000-00-00 00:00:00', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => '', 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 92, 'voucher_type_id' => 1, 'department_id' => 1, 'voucher_name' => 'PURCHASE - IMPORT2', 'prefix' => null, 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => 6256, 'cr_account_master_id' => null, 'status' => 1, 'created_at' => '2026-01-31 10:46:31', 'created_by' => 0, 'modified_at' => '2026-02-03 14:24:02', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => null, 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
                ['id' => 93, 'voucher_type_id' => 2, 'department_id' => 1, 'voucher_name' => 'PR', 'prefix' => null, 'is_prefix' => 0, 'voucher_no' => 100, 'dr_account_master_id' => null, 'cr_account_master_id' => 6256, 'status' => 1, 'created_at' => '2026-01-31 11:17:13', 'created_by' => 0, 'modified_at' => '2026-02-03 02:29:26', 'modify_by' => 0, 'deleted_at' => null, 'cash_account_id' => 0, 'bank_account_id' => 0, 'pdc_account_id' => 0, 'is_default' => 0, 'is_cash_voucher' => 0, 'default_account_id' => 0, 'description' => null, 'dr_account_master_id_to' => 0, 'cr_account_master_id_to' => 0],
        ]);
    }
}
