<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FormDetailsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('form_details')->insert([
                ['id' => 1, 'form_id' => 1, 'field_code' => 'reference_no', 'field_name' => 'Reference No', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 2, 'form_id' => 1, 'field_code' => 'lpo_no', 'field_name' => 'LPO No', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 3, 'form_id' => 1, 'field_code' => 'lpo_date', 'field_name' => 'LPO Date', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 4, 'form_id' => 1, 'field_code' => 'sales_type', 'field_name' => 'Sales Type', 'active' => 1, 'status' => 0, 'list_ord' => 0],
                ['id' => 5, 'form_id' => 1, 'field_code' => 'salesman', 'field_name' => 'Salesman', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 6, 'form_id' => 1, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 7, 'form_id' => 1, 'field_code' => 'document_type', 'field_name' => 'Document Type', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 8, 'form_id' => 1, 'field_code' => 'document_id', 'field_name' => 'Document ID', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 9, 'form_id' => 1, 'field_code' => 'terms', 'field_name' => 'Terms', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 10, 'form_id' => 1, 'field_code' => 'job', 'field_name' => 'Job', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 11, 'form_id' => 1, 'field_code' => 'location', 'field_name' => 'Location', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 12, 'form_id' => 1, 'field_code' => 'foreign_currency', 'field_name' => 'Foreign Currency', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 13, 'form_id' => 1, 'field_code' => 'footer', 'field_name' => 'Footer', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 14, 'form_id' => 2, 'field_code' => 'reference_no', 'field_name' => 'Reference No', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 15, 'form_id' => 2, 'field_code' => 'lpo_date', 'field_name' => 'LPO Date', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 16, 'form_id' => 2, 'field_code' => 'salesman', 'field_name' => 'Salesman', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 17, 'form_id' => 2, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 18, 'form_id' => 2, 'field_code' => 'document_type', 'field_name' => 'Document Type', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 19, 'form_id' => 2, 'field_code' => 'document_id', 'field_name' => 'Document ID', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 20, 'form_id' => 2, 'field_code' => 'terms', 'field_name' => 'Terms', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 21, 'form_id' => 2, 'field_code' => 'job', 'field_name' => 'Job', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 22, 'form_id' => 2, 'field_code' => 'foreign_currency', 'field_name' => 'Foreign Currency', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 23, 'form_id' => 2, 'field_code' => 'footer', 'field_name' => 'Footer', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 24, 'form_id' => 3, 'field_code' => 'reference_no', 'field_name' => 'Reference No', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 25, 'form_id' => 3, 'field_code' => 'lpo_date', 'field_name' => 'LPO Date', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 26, 'form_id' => 3, 'field_code' => 'salesman', 'field_name' => 'Salesman', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 27, 'form_id' => 3, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 29, 'form_id' => 3, 'field_code' => 'document_id', 'field_name' => 'Quotation ID', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 30, 'form_id' => 3, 'field_code' => 'terms', 'field_name' => 'Terms', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 31, 'form_id' => 3, 'field_code' => 'job', 'field_name' => 'Job', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 32, 'form_id' => 3, 'field_code' => 'foreign_currency', 'field_name' => 'Foreign Currency', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 33, 'form_id' => 3, 'field_code' => 'footer', 'field_name' => 'Footer', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 34, 'form_id' => 4, 'field_code' => 'reference_no', 'field_name' => 'Reference No', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 35, 'form_id' => 4, 'field_code' => 'lpo_date', 'field_name' => 'LPO Date', 'active' => 1, 'status' => 0, 'list_ord' => 0],
                ['id' => 36, 'form_id' => 4, 'field_code' => 'salesman', 'field_name' => 'Salesman', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 37, 'form_id' => 4, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 38, 'form_id' => 4, 'field_code' => 'job', 'field_name' => 'Job', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 39, 'form_id' => 4, 'field_code' => 'foreign_currency', 'field_name' => 'Foreign Currency', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 40, 'form_id' => 4, 'field_code' => 'footer', 'field_name' => 'Footer', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 41, 'form_id' => 4, 'field_code' => 'subject', 'field_name' => 'Subject', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 42, 'form_id' => 4, 'field_code' => 'header', 'field_name' => 'Header', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 43, 'form_id' => 5, 'field_code' => 'reference_no', 'field_name' => 'Reference No', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 44, 'form_id' => 5, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 45, 'form_id' => 5, 'field_code' => 'job', 'field_name' => 'Job', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 46, 'form_id' => 5, 'field_code' => 'location', 'field_name' => 'Location', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 47, 'form_id' => 5, 'field_code' => 'foreign_currency', 'field_name' => 'Foreign Currency', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 48, 'form_id' => 6, 'field_code' => 'reference_no', 'field_name' => 'Reference No', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 49, 'form_id' => 6, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 50, 'form_id' => 6, 'field_code' => 'job', 'field_name' => 'Job', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 51, 'form_id' => 6, 'field_code' => 'location', 'field_name' => 'Location', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 52, 'form_id' => 6, 'field_code' => 'foreign_currency', 'field_name' => 'Foreign Currency', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 53, 'form_id' => 7, 'field_code' => 'reference_no', 'field_name' => 'Reference No', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 54, 'form_id' => 7, 'field_code' => 'lpo_no', 'field_name' => 'LPO No', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 55, 'form_id' => 7, 'field_code' => 'lpo_date', 'field_name' => 'LPO Date', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 56, 'form_id' => 7, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 57, 'form_id' => 7, 'field_code' => 'document_type', 'field_name' => 'Document Type', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 58, 'form_id' => 7, 'field_code' => 'document_id', 'field_name' => 'Document ID', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 59, 'form_id' => 7, 'field_code' => 'terms', 'field_name' => 'Terms', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 60, 'form_id' => 7, 'field_code' => 'job', 'field_name' => 'Job', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 61, 'form_id' => 7, 'field_code' => 'location', 'field_name' => 'Location', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 62, 'form_id' => 7, 'field_code' => 'foreign_currency', 'field_name' => 'Foreign Currency', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 63, 'form_id' => 8, 'field_code' => 'reference_no', 'field_name' => 'Reference No', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 64, 'form_id' => 8, 'field_code' => 'lpo_date', 'field_name' => 'LPO Date', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 65, 'form_id' => 8, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 66, 'form_id' => 8, 'field_code' => 'job', 'field_name' => 'Job', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 67, 'form_id' => 8, 'field_code' => 'foreign_currency', 'field_name' => 'Foreign Currency', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 68, 'form_id' => 8, 'field_code' => 'footer', 'field_name' => 'Footer', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 69, 'form_id' => 8, 'field_code' => 'terms', 'field_name' => 'Terms', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 70, 'form_id' => 8, 'field_code' => 'header', 'field_name' => 'Header', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 71, 'form_id' => 9, 'field_code' => 'job', 'field_name' => 'Job', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 72, 'form_id' => 9, 'field_code' => 'department', 'field_name' => 'Department', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 73, 'form_id' => 9, 'field_code' => 'foreign_currency', 'field_name' => 'Foreign Currency', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 74, 'form_id' => 9, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 75, 'form_id' => 9, 'field_code' => 'depositor', 'field_name' => 'Depositor/Transfer', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 76, 'form_id' => 9, 'field_code' => 'tr_description', 'field_name' => 'Trn. Description', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 77, 'form_id' => 10, 'field_code' => 'job', 'field_name' => 'Job', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 78, 'form_id' => 10, 'field_code' => 'department', 'field_name' => 'Department', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 79, 'form_id' => 10, 'field_code' => 'foreign_currency', 'field_name' => 'Foreign Currency', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 80, 'form_id' => 10, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 81, 'form_id' => 10, 'field_code' => 'depositor', 'field_name' => 'Depositor/Transfer', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 82, 'form_id' => 10, 'field_code' => 'tr_description', 'field_name' => 'Trn. Description', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 83, 'form_id' => 1, 'field_code' => 'advance', 'field_name' => 'Advance', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 84, 'form_id' => 1, 'field_code' => 'balance', 'field_name' => 'Balance', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 85, 'form_id' => 1, 'field_code' => 'rv_entry', 'field_name' => 'Receipt Voucher Entry', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 86, 'form_id' => 1, 'field_code' => 'test', 'field_name' => 'Test', 'active' => 0, 'status' => 0, 'list_ord' => 0],
                ['id' => 87, 'form_id' => 11, 'field_code' => 'reference_no', 'field_name' => 'Reference No', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 88, 'form_id' => 11, 'field_code' => 'lpo_date', 'field_name' => 'LPO Date', 'active' => 1, 'status' => 0, 'list_ord' => 0],
                ['id' => 89, 'form_id' => 11, 'field_code' => 'salesman', 'field_name' => 'Salesman', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 90, 'form_id' => 11, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 91, 'form_id' => 11, 'field_code' => 'job', 'field_name' => 'Job', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 92, 'form_id' => 11, 'field_code' => 'foreign_currency', 'field_name' => 'Foreign Currency', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 93, 'form_id' => 11, 'field_code' => 'footer', 'field_name' => 'Footer', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 94, 'form_id' => 11, 'field_code' => 'subject', 'field_name' => 'Subject', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 95, 'form_id' => 11, 'field_code' => 'header', 'field_name' => 'Header', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 96, 'form_id' => 11, 'field_code' => 'vehicle', 'field_name' => 'Vehicle', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 97, 'form_id' => 12, 'field_code' => 'reference_no', 'field_name' => 'Reference No', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 98, 'form_id' => 12, 'field_code' => 'lpo_date', 'field_name' => 'LPO Date', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 99, 'form_id' => 12, 'field_code' => 'salesman', 'field_name' => 'Salesman', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 100, 'form_id' => 12, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 101, 'form_id' => 12, 'field_code' => 'job', 'field_name' => 'Job', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 102, 'form_id' => 12, 'field_code' => 'foreign_currency', 'field_name' => 'Foreign Currency', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 103, 'form_id' => 12, 'field_code' => 'footer', 'field_name' => 'Footer', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 104, 'form_id' => 12, 'field_code' => 'subject', 'field_name' => 'Subject', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 105, 'form_id' => 12, 'field_code' => 'header', 'field_name' => 'Header', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 106, 'form_id' => 12, 'field_code' => 'vehicle', 'field_name' => 'Vehicle', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 107, 'form_id' => 12, 'field_code' => 'document_id', 'field_name' => 'Document ID', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 108, 'form_id' => 12, 'field_code' => 'terms', 'field_name' => 'Terms', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 109, 'form_id' => 13, 'field_code' => 'foreign_currency', 'field_name' => 'Foreign Currency', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 110, 'form_id' => 13, 'field_code' => 'footer', 'field_name' => 'Footer', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 111, 'form_id' => 13, 'field_code' => 'subject', 'field_name' => 'Subject', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 112, 'form_id' => 13, 'field_code' => 'header', 'field_name' => 'Header', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 113, 'form_id' => 13, 'field_code' => 'vehicle', 'field_name' => 'Vehicle', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 114, 'form_id' => 13, 'field_code' => 'document_id', 'field_name' => 'Document ID', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 115, 'form_id' => 13, 'field_code' => 'terms', 'field_name' => 'Terms', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 116, 'form_id' => 13, 'field_code' => 'reference_no', 'field_name' => 'Reference No', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 117, 'form_id' => 13, 'field_code' => 'lpo_date', 'field_name' => 'LPO Date', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 118, 'form_id' => 13, 'field_code' => 'salesman', 'field_name' => 'Salesman', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 119, 'form_id' => 13, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 120, 'form_id' => 13, 'field_code' => 'job', 'field_name' => 'Job', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 121, 'form_id' => 13, 'field_code' => 'advance', 'field_name' => 'Advance', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 122, 'form_id' => 13, 'field_code' => 'balance', 'field_name' => 'Balance', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 123, 'form_id' => 13, 'field_code' => 'rv_entry', 'field_name' => 'Receipt Voucher Entry', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 124, 'form_id' => 13, 'field_code' => 'lpo_no', 'field_name' => 'LPO No', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 125, 'form_id' => 13, 'field_code' => 'document_type', 'field_name' => 'Document Type', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 126, 'form_id' => 13, 'field_code' => 'location', 'field_name' => 'Location', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 127, 'form_id' => 12, 'field_code' => 'kilometer', 'field_name' => 'Kilometer', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 128, 'form_id' => 13, 'field_code' => 'kilometer', 'field_name' => 'Kilometer', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 129, 'form_id' => 12, 'field_code' => 'jobtype', 'field_name' => 'Job Type', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 130, 'form_id' => 12, 'field_code' => 'jobdescription', 'field_name' => 'Job Description', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 131, 'form_id' => 13, 'field_code' => 'jobtype', 'field_name' => 'Job Type', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 132, 'form_id' => 13, 'field_code' => 'jobdescription', 'field_name' => 'Job Description', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 133, 'form_id' => 11, 'field_code' => 'jobtype', 'field_name' => 'Job Type', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 134, 'form_id' => 11, 'field_code' => 'jobdescription', 'field_name' => 'Job Description', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 135, 'form_id' => 12, 'field_code' => 'jobnature', 'field_name' => 'Job Nature', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 136, 'form_id' => 13, 'field_code' => 'jobnature', 'field_name' => 'Job Nature', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 137, 'form_id' => 12, 'field_code' => 'fabrication', 'field_name' => 'Fabrication', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 138, 'form_id' => 13, 'field_code' => 'fabrication', 'field_name' => 'Fabrication', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 139, 'form_id' => 11, 'field_code' => 'jobnature', 'field_name' => 'Job Nature', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 140, 'form_id' => 11, 'field_code' => 'fabrication', 'field_name' => 'Fabrication', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 141, 'form_id' => 11, 'field_code' => 'kilometer', 'field_name' => 'Kilometer', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 142, 'form_id' => 3, 'field_code' => 'less_amount', 'field_name' => 'Less Amount ', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 143, 'form_id' => 3, 'field_code' => 'vat_description', 'field_name' => 'VAT Description & Enable VAT Calculate from Subtotal', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 144, 'form_id' => 1, 'field_code' => 'less_amount', 'field_name' => 'Less Amount ', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 145, 'form_id' => 1, 'field_code' => 'less_prev_invoice', 'field_name' => 'Less Previous Invoice', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 146, 'form_id' => 1, 'field_code' => 'vat_description', 'field_name' => 'VAT Description & Enable VAT Calculate from Subtotal', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 147, 'form_id' => 4, 'field_code' => 'terms', 'field_name' => 'Terms', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 148, 'form_id' => 7, 'field_code' => 'item_import', 'field_name' => 'Item Import', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 149, 'form_id' => 7, 'field_code' => 'po_no', 'field_name' => 'PO No(PO auto transfer)', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 150, 'form_id' => 14, 'field_code' => 'item_code', 'field_name' => 'Item Code', 'active' => 1, 'status' => 1, 'list_ord' => 1],
                ['id' => 151, 'form_id' => 14, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 1, 'status' => 1, 'list_ord' => 2],
                ['id' => 152, 'form_id' => 14, 'field_code' => 'unit', 'field_name' => 'Unit', 'active' => 1, 'status' => 1, 'list_ord' => 3],
                ['id' => 153, 'form_id' => 14, 'field_code' => 'group', 'field_name' => 'Group', 'active' => 1, 'status' => 1, 'list_ord' => 7],
                ['id' => 154, 'form_id' => 14, 'field_code' => 'subgroup', 'field_name' => 'Subgroup', 'active' => 1, 'status' => 1, 'list_ord' => 16],
                ['id' => 155, 'form_id' => 14, 'field_code' => 'avg_cost', 'field_name' => 'Avg Cost', 'active' => 1, 'status' => 1, 'list_ord' => 6],
                ['id' => 156, 'form_id' => 14, 'field_code' => 'unit_price', 'field_name' => 'Sell Price', 'active' => 1, 'status' => 1, 'list_ord' => 7],
                ['id' => 157, 'form_id' => 14, 'field_code' => 'last_pur_cost', 'field_name' => 'Last Purchase Cost', 'active' => 1, 'status' => 1, 'list_ord' => 7],
                ['id' => 158, 'form_id' => 14, 'field_code' => 'rc_qty', 'field_name' => 'Received Quantity', 'active' => 1, 'status' => 1, 'list_ord' => 4],
                ['id' => 159, 'form_id' => 14, 'field_code' => 'is_qty', 'field_name' => 'Issued Quantity', 'active' => 1, 'status' => 1, 'list_ord' => 5],
                ['id' => 160, 'form_id' => 14, 'field_code' => 'category', 'field_name' => 'Category', 'active' => 1, 'status' => 1, 'list_ord' => 13],
                ['id' => 161, 'form_id' => 14, 'field_code' => 'subcategory', 'field_name' => 'Subcategory', 'active' => 1, 'status' => 1, 'list_ord' => 14],
                ['id' => 162, 'form_id' => 14, 'field_code' => 'model', 'field_name' => 'Model', 'active' => 1, 'status' => 1, 'list_ord' => 10],
                ['id' => 163, 'form_id' => 14, 'field_code' => 'reserve_qty', 'field_name' => 'Reserved Qty.', 'active' => 1, 'status' => 1, 'list_ord' => 15],
                ['id' => 164, 'form_id' => 14, 'field_code' => 'qty_in_hand', 'field_name' => 'Qty. in Hand', 'active' => 1, 'status' => 1, 'list_ord' => 4],
                ['id' => 165, 'form_id' => 14, 'field_code' => 'model_no', 'field_name' => 'Model No', 'active' => 1, 'status' => 1, 'list_ord' => 16],
                ['id' => 166, 'form_id' => 15, 'field_code' => 'reference_no', 'field_name' => 'Reference No', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 167, 'form_id' => 15, 'field_code' => 'lpo_date', 'field_name' => 'LPO Date', 'active' => 1, 'status' => 0, 'list_ord' => 0],
                ['id' => 168, 'form_id' => 15, 'field_code' => 'salesman', 'field_name' => 'Salesman', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 169, 'form_id' => 15, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 170, 'form_id' => 15, 'field_code' => 'job', 'field_name' => 'Job', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 171, 'form_id' => 15, 'field_code' => 'foreign_currency', 'field_name' => 'Foreign Currency', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 172, 'form_id' => 15, 'field_code' => 'footer', 'field_name' => 'Footer', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 173, 'form_id' => 15, 'field_code' => 'subject', 'field_name' => 'Subject', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 174, 'form_id' => 15, 'field_code' => 'header', 'field_name' => 'Header', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 175, 'form_id' => 15, 'field_code' => 'terms', 'field_name' => 'Terms', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 176, 'form_id' => 4, 'field_code' => 'document_id', 'field_name' => 'Document ID', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 177, 'form_id' => 0, 'field_code' => '', 'field_name' => '', 'active' => 0, 'status' => 0, 'list_ord' => 0],
                ['id' => 178, 'form_id' => 16, 'field_code' => 'reference_no', 'field_name' => 'Reference No', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 179, 'form_id' => 16, 'field_code' => 'lpo_date', 'field_name' => 'LPO Date', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 180, 'form_id' => 16, 'field_code' => 'salesman', 'field_name' => 'Salesman', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 181, 'form_id' => 16, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 182, 'form_id' => 16, 'field_code' => 'document_type', 'field_name' => 'Document Type', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 183, 'form_id' => 16, 'field_code' => 'document_id', 'field_name' => 'Document ID', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 184, 'form_id' => 16, 'field_code' => 'terms', 'field_name' => 'Terms', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 185, 'form_id' => 16, 'field_code' => 'job', 'field_name' => 'Job', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 186, 'form_id' => 16, 'field_code' => 'foreign_currency', 'field_name' => 'Foreign Currency', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 187, 'form_id' => 16, 'field_code' => 'footer', 'field_name' => 'Footer', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 188, 'form_id' => 13, 'field_code' => 'job_order_no', 'field_name' => 'Job Order No', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 189, 'form_id' => 1, 'field_code' => 'so_no', 'field_name' => 'SO No(SO auto transfer)', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 190, 'form_id' => 17, 'field_code' => 'model_no', 'field_name' => 'Model No', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 191, 'form_id' => 17, 'field_code' => 'serial_no', 'field_name' => 'Serial No', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 192, 'form_id' => 17, 'field_code' => 'machine_model', 'field_name' => 'Machine Model', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 193, 'form_id' => 17, 'field_code' => 'size', 'field_name' => 'Size', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 194, 'form_id' => 17, 'field_code' => 'other_info', 'field_name' => 'Other Information', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 195, 'form_id' => 17, 'field_code' => 'group', 'field_name' => 'Group Name', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 196, 'form_id' => 17, 'field_code' => 'subgroup', 'field_name' => 'Subgroup Name', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 197, 'form_id' => 17, 'field_code' => 'category', 'field_name' => 'Category Name', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 198, 'form_id' => 17, 'field_code' => 'subcategory', 'field_name' => 'Subcategory Name', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 199, 'form_id' => 17, 'field_code' => 'location', 'field_name' => 'Store Location', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 200, 'form_id' => 17, 'field_code' => 'assembly', 'field_name' => 'Assembly', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 201, 'form_id' => 17, 'field_code' => 'image', 'field_name' => 'Item Image', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 202, 'form_id' => 17, 'field_code' => 'p1', 'field_name' => 'P1', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 203, 'form_id' => 17, 'field_code' => 'p2', 'field_name' => 'P2', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 204, 'form_id' => 7, 'field_code' => 'purchase_type', 'field_name' => 'Purchase Type', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 205, 'form_id' => 1, 'field_code' => 'sales_type', 'field_name' => 'Sales Type', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 206, 'form_id' => 17, 'field_code' => 'supersede', 'field_name' => 'Supersede', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 207, 'form_id' => 17, 'field_code' => 'rowmaterial', 'field_name' => 'Row Material', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 208, 'form_id' => 12, 'field_code' => 'images', 'field_name' => 'Upload Images', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 209, 'form_id' => 0, 'field_code' => 'actas_tripentry', 'field_name' => 'Act as Trip Entry', 'active' => 1, 'status' => 0, 'list_ord' => 0],
                ['id' => 210, 'form_id' => 17, 'field_code' => 'surface_cost', 'field_name' => 'Surface Cost', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 211, 'form_id' => 17, 'field_code' => 'other_cost', 'field_name' => 'Other Cost', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 212, 'form_id' => 18, 'field_code' => 'reference_no', 'field_name' => 'Reference No', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 213, 'form_id' => 18, 'field_code' => 'lpo_no', 'field_name' => 'LPO No', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 214, 'form_id' => 18, 'field_code' => 'lpo_date', 'field_name' => 'LPO Date', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 215, 'form_id' => 18, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 216, 'form_id' => 18, 'field_code' => 'document_type', 'field_name' => 'Document Type', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 217, 'form_id' => 18, 'field_code' => 'document_id', 'field_name' => 'Document ID', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 218, 'form_id' => 18, 'field_code' => 'terms', 'field_name' => 'Terms', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 219, 'form_id' => 18, 'field_code' => 'job', 'field_name' => 'Job', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 220, 'form_id' => 18, 'field_code' => 'location', 'field_name' => 'Location', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 221, 'form_id' => 18, 'field_code' => 'foreign_currency', 'field_name' => 'Foreign Currency', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 222, 'form_id' => 18, 'field_code' => 'item_import', 'field_name' => 'Item Import', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 223, 'form_id' => 18, 'field_code' => 'po_no', 'field_name' => 'PO No(PO auto transfer)', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 224, 'form_id' => 18, 'field_code' => 'purchase_type', 'field_name' => 'Purchase Type', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 225, 'form_id' => 19, 'field_code' => 'jobname', 'field_name' => 'Job Code', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 226, 'form_id' => 19, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 227, 'form_id' => 19, 'field_code' => 'salesman', 'field_name' => 'salesman', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 228, 'form_id' => 19, 'field_code' => 'supplier_name', 'field_name' => 'supplier Name', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 229, 'form_id' => 1, 'field_code' => 'vehicle_no', 'field_name' => 'Vehicle No', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 230, 'form_id' => 1, 'field_code' => 'km_miles', 'field_name' => 'Kilometer/Miles', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 231, 'form_id' => 20, 'field_code' => 'code', 'field_name' => 'Job Code', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 232, 'form_id' => 20, 'field_code' => 'jobname', 'field_name' => 'Job Name', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 233, 'form_id' => 20, 'field_code' => 'open_cost', 'field_name' => 'Open Cost', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 234, 'form_id' => 20, 'field_code' => 'customer_name', 'field_name' => 'Customer', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 235, 'form_id' => 20, 'field_code' => 'department_id', 'field_name' => 'Department', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 236, 'form_id' => 20, 'field_code' => 'salesman', 'field_name' => 'Salesman', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 237, 'form_id' => 20, 'field_code' => 'open_income', 'field_name' => 'Open Income', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 238, 'form_id' => 20, 'field_code' => 'contract_amount', 'field_name' => 'Contract Amount', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 239, 'form_id' => 20, 'field_code' => 'Job Close', 'field_name' => 'job_close', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 240, 'form_id' => 20, 'field_code' => 'start_date', 'field_name' => 'Start Date', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 241, 'form_id' => 20, 'field_code' => 'end_date', 'field_name' => 'End Date', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 242, 'form_id' => 20, 'field_code' => 'transport_type', 'field_name' => 'Transport Type', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 243, 'form_id' => 20, 'field_code' => 'packing', 'field_name' => 'Packing', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 244, 'form_id' => 20, 'field_code' => 'date', 'field_name' => 'Date', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 245, 'form_id' => 20, 'field_code' => 'address', 'field_name' => 'Address', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 246, 'form_id' => 20, 'field_code' => 'mbl', 'field_name' => 'MBL/MAWB', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 247, 'form_id' => 20, 'field_code' => 'house_bl_no', 'field_name' => 'House BL No', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 248, 'form_id' => 20, 'field_code' => 'origin', 'field_name' => 'Origin', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 249, 'form_id' => 20, 'field_code' => 'hbl', 'field_name' => 'HBL/MAWB', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 250, 'form_id' => 20, 'field_code' => 'no_of_pieces', 'field_name' => 'No Of Pieces', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 251, 'form_id' => 20, 'field_code' => 'volume', 'field_name' => 'Volume', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 252, 'form_id' => 20, 'field_code' => 'gross_weight', 'field_name' => 'Gross Weight', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 253, 'form_id' => 20, 'field_code' => 'destination', 'field_name' => 'Destination', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 254, 'form_id' => 20, 'field_code' => 'flight_no', 'field_name' => 'Flight No/Vessel/Voyage', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 255, 'form_id' => 20, 'field_code' => 'chargeable_weight', 'field_name' => 'Chargeable Weight', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 256, 'form_id' => 20, 'field_code' => 'be_no', 'field_name' => 'B/E NO.', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 257, 'form_id' => 20, 'field_code' => 'flight_date', 'field_name' => 'Flight Date', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 258, 'form_id' => 20, 'field_code' => 'container_no', 'field_name' => 'Container No.', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 259, 'form_id' => 20, 'field_code' => 'por', 'field_name' => 'POR', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 260, 'form_id' => 20, 'field_code' => 'fnd', 'field_name' => 'FND', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 261, 'form_id' => 20, 'field_code' => 'document_type', 'field_name' => 'Document Type', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 262, 'form_id' => 13, 'field_code' => 'vehicle_details', 'field_name' => 'Vehicle Details', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 263, 'form_id' => 17, 'field_code' => 'bin_loc', 'field_name' => 'Bin Location', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 264, 'form_id' => 21, 'field_code' => 'job_type', 'field_name' => 'Job Type', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 265, 'form_id' => 21, 'field_code' => 'reference_no', 'field_name' => 'Reference No', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 266, 'form_id' => 21, 'field_code' => 'lpo_date', 'field_name' => 'LPO Date', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 267, 'form_id' => 21, 'field_code' => 'document_id', 'field_name' => 'Document Id', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 268, 'form_id' => 21, 'field_code' => 'vehicle', 'field_name' => 'Vehicle', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 269, 'form_id' => 21, 'field_code' => 'jobtype', 'field_name' => 'Job Type', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 270, 'form_id' => 21, 'field_code' => 'salesman', 'field_name' => 'Salesman', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 271, 'form_id' => 21, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 272, 'form_id' => 21, 'field_code' => 'kilometer', 'field_name' => 'Kilometer', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 273, 'form_id' => 21, 'field_code' => 'fuel', 'field_name' => 'Fuel Level', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 274, 'form_id' => 21, 'field_code' => 'terms', 'field_name' => 'Terms', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 275, 'form_id' => 21, 'field_code' => 'job', 'field_name' => 'Job', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 276, 'form_id' => 21, 'field_code' => 'package', 'field_name' => 'Package', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 277, 'form_id' => 21, 'field_code' => 'foreign_currency', 'field_name' => 'Foreign Currency', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 278, 'form_id' => 21, 'field_code' => 'jobdescription', 'field_name' => 'Job Description', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 279, 'form_id' => 21, 'field_code' => 'upload', 'field_name' => 'Upload Image', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 280, 'form_id' => 21, 'field_code' => 'images', 'field_name' => 'Upload Multiple', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 281, 'form_id' => 21, 'field_code' => 'dwarning', 'field_name' => 'Dashborad Wrn', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 282, 'form_id' => 21, 'field_code' => 'items_inside', 'field_name' => 'Items Inside', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 283, 'form_id' => 21, 'field_code' => 'remarks', 'field_name' => 'Remarks', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 284, 'form_id' => 21, 'field_code' => 'signature', 'field_name' => 'Signature', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 285, 'form_id' => 21, 'field_code' => 'email', 'field_name' => 'Email', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 286, 'form_id' => 21, 'field_code' => 'footer', 'field_name' => 'Footer', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 287, 'form_id' => 0, 'field_code' => '', 'field_name' => '', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 288, 'form_id' => 0, 'field_code' => '', 'field_name' => '', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 289, 'form_id' => 12, 'field_code' => 'service_date', 'field_name' => 'service_date', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 290, 'form_id' => 15, 'field_code' => 'location', 'field_name' => 'Location', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 291, 'form_id' => 15, 'field_code' => 'more_info', 'field_name' => 'More Info', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 292, 'form_id' => 15, 'field_code' => 'desc_item', 'field_name' => 'Add Description', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 293, 'form_id' => 15, 'field_code' => 'purchase_item', 'field_name' => 'Purchase', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 294, 'form_id' => 15, 'field_code' => 'sales_item', 'field_name' => 'Sales', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 295, 'form_id' => 15, 'field_code' => 'loc_item', 'field_name' => 'Location', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 296, 'form_id' => 15, 'field_code' => 'add_info', 'field_name' => 'Add Info', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 297, 'form_id' => 3, 'field_code' => 'location', 'field_name' => 'Location', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 298, 'form_id' => 3, 'field_code' => 'more_info', 'field_name' => 'More Info', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 299, 'form_id' => 3, 'field_code' => 'purchase_item', 'field_name' => 'Purchase', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 300, 'form_id' => 3, 'field_code' => 'sales_item', 'field_name' => 'Sales', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 301, 'form_id' => 3, 'field_code' => 'loc_item', 'field_name' => 'Location', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 302, 'form_id' => 3, 'field_code' => 'add_info', 'field_name' => 'Add Info', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 303, 'form_id' => 15, 'field_code' => 'location', 'field_name' => 'Location', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 304, 'form_id' => 15, 'field_code' => 'more_info', 'field_name' => 'More Info', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 305, 'form_id' => 15, 'field_code' => 'desc_item', 'field_name' => 'Add Description', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 306, 'form_id' => 15, 'field_code' => 'purchase_item', 'field_name' => 'Purchase', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 307, 'form_id' => 15, 'field_code' => 'sales_item', 'field_name' => 'Sales', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 308, 'form_id' => 15, 'field_code' => 'loc_item', 'field_name' => 'Location', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 309, 'form_id' => 15, 'field_code' => 'add_info', 'field_name' => 'Add Info', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 310, 'form_id' => 4, 'field_code' => 'location', 'field_name' => 'Location', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 311, 'form_id' => 4, 'field_code' => 'more_info', 'field_name' => 'More Info', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 312, 'form_id' => 4, 'field_code' => 'desc_item', 'field_name' => 'Add Description', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 313, 'form_id' => 4, 'field_code' => 'purchase_item', 'field_name' => 'Purchase', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 314, 'form_id' => 4, 'field_code' => 'sales_item', 'field_name' => 'Sales', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 315, 'form_id' => 4, 'field_code' => 'loc_item', 'field_name' => 'Location', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 316, 'form_id' => 4, 'field_code' => 'add_info', 'field_name' => 'Add Info', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 317, 'form_id' => 7, 'field_code' => 'more_info', 'field_name' => 'More Info', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 318, 'form_id' => 7, 'field_code' => 'supersede', 'field_name' => 'Supersede', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 319, 'form_id' => 7, 'field_code' => 'purchase', 'field_name' => 'Purchase', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 320, 'form_id' => 7, 'field_code' => 'sales', 'field_name' => 'sales', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 321, 'form_id' => 7, 'field_code' => 'location_item', 'field_name' => 'Location Item', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 322, 'form_id' => 7, 'field_code' => 'net_cost', 'field_name' => 'Net Cost', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 323, 'form_id' => 7, 'field_code' => 'other_cost', 'field_name' => 'Other Cost', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 324, 'form_id' => 8, 'field_code' => 'location', 'field_name' => 'Location', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 325, 'form_id' => 8, 'field_code' => 'more_info', 'field_name' => 'More Info', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 326, 'form_id' => 8, 'field_code' => 'purchase', 'field_name' => 'Purchase', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 327, 'form_id' => 8, 'field_code' => 'sales', 'field_name' => 'Sales', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 328, 'form_id' => 8, 'field_code' => 'location_item', 'field_name' => 'Location item', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 329, 'form_id' => 8, 'field_code' => 'net_cost', 'field_name' => 'Net Cost', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 330, 'form_id' => 8, 'field_code' => 'other_cost', 'field_name' => 'Other Cost', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 331, 'form_id' => 8, 'field_code' => 'add_info', 'field_name' => 'Add Info', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 332, 'form_id' => 19, 'field_code' => 'location', 'field_name' => 'Location', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 333, 'form_id' => 19, 'field_code' => 'more_info', 'field_name' => 'More info', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 334, 'form_id' => 19, 'field_code' => 'location_item', 'field_name' => 'Location Item', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 335, 'form_id' => 3, 'field_code' => 'location', 'field_name' => 'Location', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 336, 'form_id' => 3, 'field_code' => 'more_info', 'field_name' => 'More Info', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 337, 'form_id' => 3, 'field_code' => 'purchase_item', 'field_name' => 'Purchase', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 338, 'form_id' => 3, 'field_code' => 'sales_item', 'field_name' => 'Sales', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 339, 'form_id' => 3, 'field_code' => 'location_item', 'field_name' => 'Location', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 340, 'form_id' => 3, 'field_code' => 'add_desc', 'field_name' => 'Add Description', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 341, 'form_id' => 2, 'field_code' => 'location', 'field_name' => 'Location', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 342, 'form_id' => 2, 'field_code' => 'more_info', 'field_name' => 'More Info', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 343, 'form_id' => 2, 'field_code' => 'purchase_item', 'field_name' => 'Purchase', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 344, 'form_id' => 2, 'field_code' => 'sales_item', 'field_name' => 'Sales', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 345, 'form_id' => 2, 'field_code' => 'location_item', 'field_name' => 'Location Item', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 346, 'form_id' => 2, 'field_code' => 'add_info', 'field_name' => 'Add Info', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 347, 'form_id' => 1, 'field_code' => 'supersede', 'field_name' => 'Supersede', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 348, 'form_id' => 1, 'field_code' => 'more_info', 'field_name' => 'More Info', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 349, 'form_id' => 1, 'field_code' => 'purchase_item', 'field_name' => 'Purchase', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 350, 'form_id' => 1, 'field_code' => 'sales_item', 'field_name' => 'Sales', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 351, 'form_id' => 1, 'field_code' => 'location_item', 'field_name' => 'Location', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 352, 'form_id' => 1, 'field_code' => 'add_info', 'field_name' => 'Add Info', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 353, 'form_id' => 1, 'field_code' => 'customer_sales', 'field_name' => 'Customer Sales', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 354, 'form_id' => 1, 'field_code' => 'add_assembley', 'field_name' => 'Assembly Items', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 355, 'form_id' => 1, 'field_code' => 'view_assembley', 'field_name' => 'View Assembly Items', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 356, 'form_id' => 1, 'field_code' => 'add_desc', 'field_name' => 'Add Description', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 357, 'form_id' => 22, 'field_code' => 'reference_no', 'field_name' => 'Reference No', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 358, 'form_id' => 22, 'field_code' => 'document_id', 'field_name' => 'Document Id', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 359, 'form_id' => 22, 'field_code' => 'terms', 'field_name' => 'Terms', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 360, 'form_id' => 22, 'field_code' => 'job', 'field_name' => 'Job', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 361, 'form_id' => 22, 'field_code' => 'foreign_currency', 'field_name' => 'Foreign Currency', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 362, 'form_id' => 22, 'field_code' => 'more_info', 'field_name' => 'More Info', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 363, 'form_id' => 22, 'field_code' => 'sales', 'field_name' => 'sales', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 364, 'form_id' => 22, 'field_code' => 'purchase', 'field_name' => 'Purchase', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 365, 'form_id' => 22, 'field_code' => 'header', 'field_name' => 'Header', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 366, 'form_id' => 22, 'field_code' => 'footer', 'field_name' => 'Footer', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 367, 'form_id' => 25, 'field_code' => 'salesman', 'field_name' => 'Salesman', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 368, 'form_id' => 25, 'field_code' => 'credit_limit', 'field_name' => 'Credit Limit', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 369, 'form_id' => 25, 'field_code' => 'due_days', 'field_name' => 'Due Days', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 370, 'form_id' => 25, 'field_code' => 'terms', 'field_name' => 'Terms', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 371, 'form_id' => 25, 'field_code' => 'vat_assignable', 'field_name' => 'VAT Assignable', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 372, 'form_id' => 25, 'field_code' => 'job_assignable', 'field_name' => 'Job Assignable', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 373, 'form_id' => 25, 'field_code' => 'job_compulsary', 'field_name' => 'Job Compulsary', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 374, 'form_id' => 25, 'field_code' => 'hide', 'field_name' => 'Hide', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 375, 'form_id' => 21, 'field_code' => 'service_date', 'field_name' => 'Service Details', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 376, 'form_id' => 23, 'field_code' => 'reference_no', 'field_name' => 'Reference No', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 377, 'form_id' => 23, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 378, 'form_id' => 23, 'field_code' => 'location', 'field_name' => 'Location', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 379, 'form_id' => 23, 'field_code' => 'other_cost', 'field_name' => 'Other Cost', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 380, 'form_id' => 24, 'field_code' => 'reference_no', 'field_name' => 'Reference No', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 381, 'form_id' => 24, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 382, 'form_id' => 24, 'field_code' => 'location', 'field_name' => 'Location', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 383, 'form_id' => 1, 'field_code' => 'crm_details', 'field_name' => 'Crm Details', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 384, 'form_id' => 0, 'field_code' => '', 'field_name' => '', 'active' => 0, 'status' => 0, 'list_ord' => 0],
                ['id' => 385, 'form_id' => 17, 'field_code' => 'simple_entry', 'field_name' => 'Simple Entry(Unit/Open Qty/Open Cost/Vat)', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 386, 'form_id' => 3, 'field_code' => 'customer_area', 'field_name' => 'Customer Area', 'active' => 0, 'status' => 1, 'list_ord' => 2],
                ['id' => 387, 'form_id' => 3, 'field_code' => 'customer_contact_person', 'field_name' => 'Customer Contact Person', 'active' => 0, 'status' => 1, 'list_ord' => 5],
                ['id' => 388, 'form_id' => 3, 'field_code' => 'customer_trn', 'field_name' => 'Customer TRN No', 'active' => 0, 'status' => 1, 'list_ord' => 4],
                ['id' => 389, 'form_id' => 3, 'field_code' => 'customer_department', 'field_name' => 'Customer Department', 'active' => 0, 'status' => 1, 'list_ord' => 6],
                ['id' => 390, 'form_id' => 3, 'field_code' => 'customer_country', 'field_name' => 'Customer Country', 'active' => 1, 'status' => 1, 'list_ord' => 1],
                ['id' => 391, 'form_id' => 3, 'field_code' => 'customer_email', 'field_name' => 'Customer Email', 'active' => 1, 'status' => 1, 'list_ord' => 3],
                ['id' => 392, 'form_id' => 25, 'field_code' => 'customer_area', 'field_name' => 'Customer Area', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 393, 'form_id' => 25, 'field_code' => 'customer_country', 'field_name' => 'Customer Country', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 394, 'form_id' => 25, 'field_code' => 'customer_email', 'field_name' => 'Customer Email', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 395, 'form_id' => 25, 'field_code' => 'customer_contact_person', 'field_name' => 'Customer Contact Person', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 396, 'form_id' => 25, 'field_code' => 'customer_trn', 'field_name' => 'Customer TRN No', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 397, 'form_id' => 25, 'field_code' => 'supplier_country', 'field_name' => 'Supplier Country', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 398, 'form_id' => 25, 'field_code' => 'supplier_area', 'field_name' => 'Supplier Area', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 399, 'form_id' => 25, 'field_code' => 'supplier_email', 'field_name' => 'Supplier Email', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 400, 'form_id' => 25, 'field_code' => 'supplier_contact_person', 'field_name' => 'Supplier Contact Person', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 401, 'form_id' => 25, 'field_code' => 'supplier_trn', 'field_name' => 'Supplier TRN No', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 402, 'form_id' => 8, 'field_code' => 'supplier_country', 'field_name' => 'Supplier Country', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 403, 'form_id' => 8, 'field_code' => 'supplier_area', 'field_name' => 'Supplier Area', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 404, 'form_id' => 8, 'field_code' => 'supplier_email', 'field_name' => 'Supplier Email', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 405, 'form_id' => 8, 'field_code' => 'supplier_contact_person', 'field_name' => 'Supplier Contact Person', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 406, 'form_id' => 8, 'field_code' => 'supplier_trn', 'field_name' => 'Supplier TRN No', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 407, 'form_id' => 8, 'field_code' => 'supplier_department', 'field_name' => 'Supplier Department', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 408, 'form_id' => 25, 'field_code' => 'account_address', 'field_name' => 'Account Address', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 409, 'form_id' => 25, 'field_code' => 'account_country', 'field_name' => 'Account Country', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 410, 'form_id' => 25, 'field_code' => 'account_area', 'field_name' => 'Account Area', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 411, 'form_id' => 25, 'field_code' => 'account_phone', 'field_name' => 'Account Phone', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 412, 'form_id' => 25, 'field_code' => 'account_email', 'field_name' => 'Account Email', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 413, 'form_id' => 25, 'field_code' => 'account_trn', 'field_name' => 'Account TRN No', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 414, 'form_id' => 1, 'field_code' => 'customer_address', 'field_name' => 'Customer Address', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 415, 'form_id' => 1, 'field_code' => 'customer_country', 'field_name' => 'Customer Country', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 416, 'form_id' => 1, 'field_code' => 'customer_area', 'field_name' => 'Customer Area', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 417, 'form_id' => 1, 'field_code' => 'customer_phone', 'field_name' => 'Customer Phone', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 418, 'form_id' => 1, 'field_code' => 'customer_trn', 'field_name' => 'Customer TRN No', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 419, 'form_id' => 7, 'field_code' => 'suppplier_address', 'field_name' => 'Supplier Address', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 420, 'form_id' => 7, 'field_code' => 'supplier_country', 'field_name' => 'Supplier Country', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 421, 'form_id' => 7, 'field_code' => 'supplier_area', 'field_name' => 'Supplier Area', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 422, 'form_id' => 7, 'field_code' => 'supplier_phone', 'field_name' => 'Supplier Phone', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 423, 'form_id' => 7, 'field_code' => 'supplier_trn', 'field_name' => 'Supplier TRN No', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 424, 'form_id' => 25, 'field_code' => 'account_vat', 'field_name' => 'Vat Visibility', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 425, 'form_id' => 25, 'field_code' => 'account_transaction', 'field_name' => 'Account Transaction Type', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 426, 'form_id' => 25, 'field_code' => 'vat_per', 'field_name' => 'Vat Percentage', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 427, 'form_id' => 25, 'field_code' => 'ob_other_details', 'field_name' => 'OB Other detail', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 428, 'form_id' => 1, 'field_code' => 'images', 'field_name' => 'Images Upload', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 429, 'form_id' => 11, 'field_code' => 'items_description', 'field_name' => 'Items Description', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 430, 'form_id' => 12, 'field_code' => 'items_description', 'field_name' => 'Items Description', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 431, 'form_id' => 13, 'field_code' => 'items_description', 'field_name' => 'Items Description', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 432, 'form_id' => 9, 'field_code' => 'salesman', 'field_name' => 'salesman', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 433, 'form_id' => 8, 'field_code' => 'copy_from', 'field_name' => 'Copy From', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 434, 'form_id' => 22, 'field_code' => 'salesman', 'field_name' => 'Salesman', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 435, 'form_id' => 22, 'field_code' => 'subject', 'field_name' => 'Subject', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 436, 'form_id' => 22, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 437, 'form_id' => 22, 'field_code' => 'copy_from', 'field_name' => 'Copy From', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 438, 'form_id' => 4, 'field_code' => 'copy_from', 'field_name' => 'Copy From', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 439, 'form_id' => 2, 'field_code' => 'copy_from', 'field_name' => 'Copy From', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 440, 'form_id' => 18, 'field_code' => 'copy_from', 'field_name' => 'Copy From', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 441, 'form_id' => 3, 'field_code' => 'copy_from', 'field_name' => 'Copy From', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 442, 'form_id' => 7, 'field_code' => 'copy_from', 'field_name' => 'Copy From', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 443, 'form_id' => 0, 'field_code' => '', 'field_name' => '', 'active' => 0, 'status' => 0, 'list_ord' => 0],
                ['id' => 444, 'form_id' => 0, 'field_code' => '', 'field_name' => '', 'active' => 0, 'status' => 0, 'list_ord' => 0],
                ['id' => 445, 'form_id' => 1, 'field_code' => 'copy_from', 'field_name' => 'Copy From', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 446, 'form_id' => 11, 'field_code' => 'copy_from', 'field_name' => 'Copy From', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 447, 'form_id' => 12, 'field_code' => 'copy_from', 'field_name' => 'Copy From', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 448, 'form_id' => 13, 'field_code' => 'copy_from', 'field_name' => 'Copy From', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 449, 'form_id' => 8, 'field_code' => 'footer_custom', 'field_name' => 'Footer Edit', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 450, 'form_id' => 1, 'field_code' => 'send_email', 'field_name' => 'Invoice send to Email', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 451, 'form_id' => 7, 'field_code' => 'send_email', 'field_name' => 'Invoice send to Email', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 452, 'form_id' => 6, 'field_code' => 'send_email', 'field_name' => 'Invoice send to Email', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 453, 'form_id' => 5, 'field_code' => 'send_email', 'field_name' => 'Invoice send to Email', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 455, 'form_id' => 4, 'field_code' => 'footer_editable', 'field_name' => 'Footer Editable', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 456, 'form_id' => 1, 'field_code' => 'copy_from_loc', 'field_name' => 'Copy From LOC', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 457, 'form_id' => 1, 'field_code' => 'dimension', 'field_name' => 'Dimension', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 458, 'form_id' => 1, 'field_code' => 'selling_expense', 'field_name' => 'Selling Expense', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 459, 'form_id' => 3, 'field_code' => 'supplementary_job', 'field_name' => 'Supplementary Job', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 460, 'form_id' => 3, 'field_code' => 'select_po', 'field_name' => 'Select PO', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 461, 'form_id' => 2, 'field_code' => 'add_description', 'field_name' => 'Add Description', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 462, 'form_id' => 5, 'field_code' => 'sr_account', 'field_name' => 'SR Account', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 463, 'form_id' => 5, 'field_code' => 'more_info', 'field_name' => 'More Info', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 464, 'form_id' => 5, 'field_code' => 'item_location', 'field_name' => 'Item Location', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 465, 'form_id' => 5, 'field_code' => 'supersede', 'field_name' => 'Supersede', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 466, 'form_id' => 5, 'field_code' => 'purchase', 'field_name' => 'Purchase', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 467, 'form_id' => 5, 'field_code' => 'sales', 'field_name' => 'Sales', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 468, 'form_id' => 8, 'field_code' => 'add_desc', 'field_name' => 'Add Desc', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 469, 'form_id' => 7, 'field_code' => 'dimension', 'field_name' => 'Dimension', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 470, 'form_id' => 6, 'field_code' => 'pi_no', 'field_name' => 'PI No:', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 471, 'form_id' => 6, 'field_code' => 'more_info', 'field_name' => 'More Info', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 472, 'form_id' => 6, 'field_code' => 'supersede', 'field_name' => 'Supersede', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 473, 'form_id' => 6, 'field_code' => 'purchase', 'field_name' => 'Purchase', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 474, 'form_id' => 6, 'field_code' => 'sales', 'field_name' => 'Sales', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 475, 'form_id' => 6, 'field_code' => 'location_item', 'field_name' => 'Location Item', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 476, 'form_id' => 6, 'field_code' => 'other_cost', 'field_name' => 'Other Cost', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 477, 'form_id' => 12, 'field_code' => 'more_info', 'field_name' => 'More Info', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 478, 'form_id' => 12, 'field_code' => 'purchase', 'field_name' => 'Purchase', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 479, 'form_id' => 12, 'field_code' => 'sales', 'field_name' => 'Sales', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 480, 'form_id' => 11, 'field_code' => 'more_info', 'field_name' => 'More Info', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 481, 'form_id' => 11, 'field_code' => 'add_desc', 'field_name' => 'Add Desc', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 482, 'form_id' => 11, 'field_code' => 'purchase', 'field_name' => 'Purchase', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 483, 'form_id' => 11, 'field_code' => 'sales', 'field_name' => 'Sales', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 484, 'form_id' => 13, 'field_code' => 'job_account', 'field_name' => 'Job Account', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 485, 'form_id' => 13, 'field_code' => 'add_info', 'field_name' => 'More Info', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 486, 'form_id' => 13, 'field_code' => 'add_desc', 'field_name' => 'Add Description', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 487, 'form_id' => 13, 'field_code' => 'item_location', 'field_name' => 'Item Location', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 488, 'form_id' => 13, 'field_code' => 'purchase', 'field_name' => 'Purchase', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 489, 'form_id' => 13, 'field_code' => 'sales', 'field_name' => 'Sales', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 490, 'form_id' => 18, 'field_code' => 'more_info', 'field_name' => 'More Info', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 491, 'form_id' => 18, 'field_code' => 'purchase', 'field_name' => 'Purchase', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 492, 'form_id' => 18, 'field_code' => 'sales', 'field_name' => 'Sales', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 493, 'form_id' => 18, 'field_code' => 'net_cost', 'field_name' => 'Net Cost', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 494, 'form_id' => 18, 'field_code' => 'item_loc', 'field_name' => 'Item Location', 'active' => 0, 'status' => 0, 'list_ord' => 0],
                ['id' => 495, 'form_id' => 18, 'field_code' => 'supersede', 'field_name' => 'Supersede', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 496, 'form_id' => 18, 'field_code' => 'other_cost', 'field_name' => 'Other Cost', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 497, 'form_id' => 16, 'field_code' => 'more_info', 'field_name' => 'More Info', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 498, 'form_id' => 16, 'field_code' => 'purchase', 'field_name' => 'Purchase', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 499, 'form_id' => 16, 'field_code' => 'sales', 'field_name' => 'Sales', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 500, 'form_id' => 16, 'field_code' => 'add_info', 'field_name' => 'Add Info', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 501, 'form_id' => 26, 'field_code' => 'job_entry', 'field_name' => 'Job Entry', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 502, 'form_id' => 26, 'field_code' => 'job_code', 'field_name' => 'Job Code', 'active' => 1, 'status' => 1, 'list_ord' => 0],
        ]);

        DB::table('form_details')->insert([
                ['id' => 503, 'form_id' => 26, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 504, 'form_id' => 26, 'field_code' => 'more_info', 'field_name' => 'More Info', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 505, 'form_id' => 26, 'field_code' => 'item_location', 'field_name' => 'Item Location', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 506, 'form_id' => 27, 'field_code' => 'transfer_in', 'field_name' => 'Transfer In', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 507, 'form_id' => 27, 'field_code' => 'transfer_out', 'field_name' => 'Transfer Out', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 508, 'form_id' => 27, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 509, 'form_id' => 27, 'field_code' => 'production', 'field_name' => 'Production', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 510, 'form_id' => 27, 'field_code' => 'more_info', 'field_name' => 'More Info', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 511, 'form_id' => 27, 'field_code' => 'purchase', 'field_name' => 'Purchase', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 512, 'form_id' => 27, 'field_code' => 'sales', 'field_name' => 'Sales', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 513, 'form_id' => 27, 'field_code' => 'item_loc', 'field_name' => 'Item Location', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 514, 'form_id' => 27, 'field_code' => 'rawmaterial', 'field_name' => 'Rawmaterial', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 515, 'form_id' => 27, 'field_code' => 'add_rawmaterial', 'field_name' => 'Add Raw Material', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 516, 'form_id' => 27, 'field_code' => 'net_cost', 'field_name' => 'Net Cost', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 517, 'form_id' => 27, 'field_code' => 'other_cost', 'field_name' => 'Other Cost', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 518, 'form_id' => 27, 'field_code' => 'wastage', 'field_name' => 'Wastage Entry', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 519, 'form_id' => 9, 'field_code' => 'reference', 'field_name' => 'Reference', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 520, 'form_id' => 10, 'field_code' => 'reference', 'field_name' => 'Reference', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 522, 'form_id' => 9, 'field_code' => 'send_email', 'field_name' => 'Send Email', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 523, 'form_id' => 10, 'field_code' => 'send_email', 'field_name' => 'Send Email', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 524, 'form_id' => 22, 'field_code' => 'footer_custom', 'field_name' => 'Footer Edit', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 525, 'form_id' => 3, 'field_code' => 'footer_edit', 'field_name' => 'Footer Edit', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 526, 'form_id' => 7, 'field_code' => 'footer_edit', 'field_name' => 'Footer Edit', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 527, 'form_id' => 1, 'field_code' => 'footer_edit', 'field_name' => 'Footer Edit', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 528, 'form_id' => 2, 'field_code' => 'footer_edit', 'field_name' => 'Footer Edit', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 529, 'form_id' => 5, 'field_code' => 'footer_edit', 'field_name' => 'Footer Edit', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 530, 'form_id' => 6, 'field_code' => 'footer_edit', 'field_name' => 'Footer Edit', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 531, 'form_id' => 18, 'field_code' => 'footer_edit', 'field_name' => 'Footer Edit', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 532, 'form_id' => 26, 'field_code' => 'footer_edit', 'field_name' => 'Footer  Edit', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 533, 'form_id' => 16, 'field_code' => 'footer_edit', 'field_name' => 'Footer Edit', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 534, 'form_id' => 27, 'field_code' => 'footer_edit', 'field_name' => 'Footer Edit', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 535, 'form_id' => 11, 'field_code' => 'footer_edit', 'field_name' => 'Footer Edit', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 536, 'form_id' => 12, 'field_code' => 'footer_edit', 'field_name' => 'Footer Edit', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 537, 'form_id' => 13, 'field_code' => 'footer_edit', 'field_name' => 'Footer Edit', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 538, 'form_id' => 14, 'field_code' => 'item_width', 'field_name' => 'Item Width', 'active' => 1, 'status' => 1, 'list_ord' => 17],
                ['id' => 539, 'form_id' => 14, 'field_code' => 'item_length', 'field_name' => 'Item Length', 'active' => 1, 'status' => 1, 'list_ord' => 18],
                ['id' => 540, 'form_id' => 14, 'field_code' => 'mp_quantity', 'field_name' => 'MP Quantity', 'active' => 1, 'status' => 1, 'list_ord' => 19],
                ['id' => 541, 'form_id' => 28, 'field_code' => 'passport', 'field_name' => 'Passport', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 542, 'form_id' => 28, 'field_code' => 'visa', 'field_name' => 'Visa', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 543, 'form_id' => 28, 'field_code' => 'labour_card', 'field_name' => 'Labour Card', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 544, 'form_id' => 28, 'field_code' => 'health_card', 'field_name' => 'Health Card', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 545, 'form_id' => 28, 'field_code' => 'id_card', 'field_name' => 'ID Card', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 546, 'form_id' => 28, 'field_code' => 'medical_exam', 'field_name' => 'Medical Exam', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 547, 'form_id' => 6, 'field_code' => 'net_cost', 'field_name' => 'Net Cost', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 548, 'form_id' => 29, 'field_code' => 'reference_no', 'field_name' => 'Reference No', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 549, 'form_id' => 29, 'field_code' => 'trn_no', 'field_name' => 'TRN No:', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 550, 'form_id' => 29, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 551, 'form_id' => 29, 'field_code' => 'job', 'field_name' => 'JOB', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 552, 'form_id' => 29, 'field_code' => 'foreign_currency', 'field_name' => 'Foreign Currency', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 553, 'form_id' => 29, 'field_code' => 'item_import', 'field_name' => 'Item Import', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 554, 'form_id' => 30, 'field_code' => 'reference_no', 'field_name' => 'Reference No:', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 555, 'form_id' => 30, 'field_code' => 'trn_no', 'field_name' => 'TRN No:', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 556, 'form_id' => 30, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 557, 'form_id' => 30, 'field_code' => 'job', 'field_name' => 'JOB', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 558, 'form_id' => 30, 'field_code' => 'foreign_currency', 'field_name' => 'Foreign Currency', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 559, 'form_id' => 30, 'field_code' => 'item_import', 'field_name' => 'Item Import', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 560, 'form_id' => 13, 'field_code' => 'export', 'field_name' => 'Export', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 561, 'form_id' => 30, 'field_code' => 'footer_edit', 'field_name' => 'Footer Edit', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 562, 'form_id' => 29, 'field_code' => 'footer_edit', 'field_name' => 'Footer Edit', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 563, 'form_id' => 17, 'field_code' => 'description_arabic', 'field_name' => 'Item Description Arabic', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 564, 'form_id' => 31, 'field_code' => 'area', 'field_name' => 'Area', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 565, 'form_id' => 31, 'field_code' => 'country', 'field_name' => 'Country', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 566, 'form_id' => 31, 'field_code' => 'email', 'field_name' => 'Email', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 567, 'form_id' => 31, 'field_code' => 'contact_person', 'field_name' => 'Contact Person', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 568, 'form_id' => 31, 'field_code' => 'trn_no', 'field_name' => 'TRN NO', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 569, 'form_id' => 31, 'field_code' => 'salesman', 'field_name' => 'Salesman', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 570, 'form_id' => 31, 'field_code' => 'credit_limit', 'field_name' => 'Credit Limit', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 571, 'form_id' => 31, 'field_code' => 'due_days', 'field_name' => 'Due Days', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 572, 'form_id' => 31, 'field_code' => 'terms', 'field_name' => 'Terms', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 573, 'form_id' => 30, 'field_code' => 'vehicle', 'field_name' => 'Vehicle', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 574, 'form_id' => 7, 'field_code' => 'pv_entry', 'field_name' => 'Payment Voucher Entry', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 575, 'form_id' => 11, 'field_code' => 'export', 'field_name' => 'Export', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 576, 'form_id' => 11, 'field_code' => 'image', 'field_name' => 'Image Upload', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 577, 'form_id' => 12, 'field_code' => 'export', 'field_name' => 'Export', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 578, 'form_id' => 11, 'field_code' => 'add_info', 'field_name' => 'Add Info', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 579, 'form_id' => 12, 'field_code' => 'add_info', 'field_name' => 'Add Info', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 580, 'form_id' => 13, 'field_code' => 'images', 'field_name' => 'Image Upload', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 581, 'form_id' => 21, 'field_code' => 'footer_edit', 'field_name' => 'Footer Edit', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 582, 'form_id' => 21, 'field_code' => 'export', 'field_name' => 'Export', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 583, 'form_id' => 21, 'field_code' => 'add_info', 'field_name' => 'Add Info', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 584, 'form_id' => 21, 'field_code' => 'items_description', 'field_name' => 'Items Description', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 585, 'form_id' => 21, 'field_code' => 'more_info', 'field_name' => 'More Info', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 586, 'form_id' => 21, 'field_code' => 'purchase', 'field_name' => 'Purchase', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 587, 'form_id' => 21, 'field_code' => 'sales', 'field_name' => 'Sales', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 588, 'form_id' => 4, 'field_code' => 'item_import', 'field_name' => 'Item Import', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 589, 'form_id' => 15, 'field_code' => 'item_import', 'field_name' => 'Item Import', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 590, 'form_id' => 8, 'field_code' => 'document_type', 'field_name' => 'Document Type', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 591, 'form_id' => 8, 'field_code' => 'document_so', 'field_name' => 'Sales Order', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 592, 'form_id' => 3, 'field_code' => 'order_type', 'field_name' => 'Order Type', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 593, 'form_id' => 10, 'field_code' => 'multi_entry', 'field_name' => 'Multi Entry', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 594, 'form_id' => 9, 'field_code' => 'multi_entry', 'field_name' => 'Multi Entry', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 595, 'form_id' => 32, 'field_code' => 'reference_no', 'field_name' => 'Reference No', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 596, 'form_id' => 32, 'field_code' => 'trn_no', 'field_name' => 'TRN No:', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 597, 'form_id' => 32, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 598, 'form_id' => 32, 'field_code' => 'job', 'field_name' => 'JOB', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 600, 'form_id' => 32, 'field_code' => 'foreign_currency', 'field_name' => 'Foreign Currency', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 601, 'form_id' => 32, 'field_code' => 'footer_edit', 'field_name' => 'Footer Edit', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 602, 'form_id' => 32, 'field_code' => 'vehicle', 'field_name' => 'Vehicle', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 603, 'form_id' => 20, 'field_code' => 'shipper', 'field_name' => 'Shipper', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 604, 'form_id' => 20, 'field_code' => 'consignee', 'field_name' => 'Consignee', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 606, 'form_id' => 33, 'field_code' => 'reference_no', 'field_name' => 'Reference No', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 607, 'form_id' => 33, 'field_code' => 'trn_no', 'field_name' => 'TRN No:', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 608, 'form_id' => 33, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 609, 'form_id' => 33, 'field_code' => 'job', 'field_name' => 'JOB', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 610, 'form_id' => 33, 'field_code' => 'foreign_currency', 'field_name' => 'Foreign Currency', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 611, 'form_id' => 33, 'field_code' => 'item_import', 'field_name' => 'Item Import', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 612, 'form_id' => 33, 'field_code' => 'footer_edit', 'field_name' => 'Footer Edit', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 613, 'form_id' => 18, 'field_code' => 'location_item', 'field_name' => 'Location Item', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 614, 'form_id' => 32, 'field_code' => 'item_import', 'field_name' => 'Item Import', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 615, 'form_id' => 5, 'field_code' => 'dimension', 'field_name' => 'Dimension', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 616, 'form_id' => 6, 'field_code' => 'dimension', 'field_name' => 'Dimension', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 617, 'form_id' => 25, 'field_code' => 'ac_no', 'field_name' => 'Account No', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 618, 'form_id' => 4, 'field_code' => 'document_upload', 'field_name' => 'document upload', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 619, 'form_id' => 3, 'field_code' => 'due_date', 'field_name' => 'due date', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 620, 'form_id' => 7, 'field_code' => 'due_dates', 'field_name' => 'due dates', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 621, 'form_id' => 34, 'field_code' => 'jobname', 'field_name' => 'Job Code', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 622, 'form_id' => 34, 'field_code' => 'description', 'field_name' => 'Description', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 623, 'form_id' => 34, 'field_code' => 'salesman', 'field_name' => 'Salesman', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 624, 'form_id' => 34, 'field_code' => 'supplier_name', 'field_name' => 'Supplier Name', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 625, 'form_id' => 34, 'field_code' => 'location', 'field_name' => 'Location', 'active' => 1, 'status' => 1, 'list_ord' => 0],
                ['id' => 626, 'form_id' => 34, 'field_code' => 'more_info', 'field_name' => 'More Info', 'active' => 0, 'status' => 1, 'list_ord' => 0],
                ['id' => 627, 'form_id' => 34, 'field_code' => 'location_item', 'field_name' => 'Location Item', 'active' => 1, 'status' => 1, 'list_ord' => 0],
        ]);
    }
}
