<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProformaInvoiceItemSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('proforma_invoice_item')->insert([
                ['id' => 1, 'proforma_invoice_id' => 1, 'item_id' => 8164, 'item_name' => 'LLX 620 - L Inset Kitchen Sink, 2 Bowls  no Drainer (Waste kit and bottle trap included)', 'unit_id' => 1, 'quantity' => 5, 'unit_price' => 591.36, 'vat' => 5, 'vat_amount' => 147.84, 'discount' => 0, 'line_total' => 2956.8, 'is_transfer' => 0, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 2956.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 2956.8, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 2, 'proforma_invoice_id' => 1, 'item_id' => 8195, 'item_name' => 'NPX 611 RHD Inset Kitchen Sink slimtop, Single Bowl + Drainer, Stainless Steel AISI 304, 860 L * 510 W, Bowl depth 200 m', 'unit_id' => 1, 'quantity' => 2, 'unit_price' => 1243.2, 'vat' => 5, 'vat_amount' => 124.32, 'discount' => 0, 'line_total' => 2486.4, 'is_transfer' => 0, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 2486.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 2486.4, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 3, 'proforma_invoice_id' => 2, 'item_id' => 9989, 'item_name' => 'D-Code Toilet seat ring, elongated, hinges stainless steel, without soft closure', 'unit_id' => 1, 'quantity' => 5, 'unit_price' => 180.32, 'vat' => 5, 'vat_amount' => 45.08, 'discount' => 0, 'line_total' => 901.6, 'is_transfer' => 0, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 901.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 901.6, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 4, 'proforma_invoice_id' => 3, 'item_id' => 9213, 'item_name' => 'Darling New Siphon cover', 'unit_id' => 1, 'quantity' => 10, 'unit_price' => 452.98, 'vat' => 5, 'vat_amount' => 226.49, 'discount' => 0, 'line_total' => 4529.8, 'is_transfer' => 1, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 4529.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 4529.8, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 5, 'proforma_invoice_id' => 4, 'item_id' => 972, 'item_name' => 'Integra Wall-hung WC Pan hidden fixation, 54 cm', 'unit_id' => 1, 'quantity' => 310, 'unit_price' => 310, 'vat' => 5, 'vat_amount' => 4805.0, 'discount' => 0, 'line_total' => 96100.0, 'is_transfer' => 2, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => -246, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 96100.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 96100.0, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 6, 'proforma_invoice_id' => 4, 'item_id' => 983, 'item_name' => 'Universal Slim WC Seat & Cover (Duroplast, Soft-Closing)', 'unit_id' => 1, 'quantity' => 310, 'unit_price' => 95, 'vat' => 5, 'vat_amount' => 1472.5, 'discount' => 0, 'line_total' => 29450.0, 'is_transfer' => 1, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 29450.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 125550.0, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 7, 'proforma_invoice_id' => 4, 'item_id' => 2389, 'item_name' => 'Bidet Handshower, Plastic, G 3/8”- G 1/2” connector included', 'unit_id' => 1, 'quantity' => 315, 'unit_price' => 56, 'vat' => 5, 'vat_amount' => 882.0, 'discount' => 0, 'line_total' => 17640.0, 'is_transfer' => 1, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 17640.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 143190.0, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 8, 'proforma_invoice_id' => 4, 'item_id' => 2208, 'item_name' => 'Minimax S Basin Mixer (With Pop-Up)', 'unit_id' => 1, 'quantity' => 312, 'unit_price' => 180, 'vat' => 5, 'vat_amount' => 2808.0, 'discount' => 0, 'line_total' => 56160.0, 'is_transfer' => 2, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => -290, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 56160.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 199350.0, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 9, 'proforma_invoice_id' => 4, 'item_id' => 2254, 'item_name' => 'Fold S Bath/Shower Mixer', 'unit_id' => 1, 'quantity' => 312, 'unit_price' => 200, 'vat' => 5, 'vat_amount' => 3120.0, 'discount' => 0, 'line_total' => 62400.0, 'is_transfer' => 0, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 62400.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 261750.0, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 10, 'proforma_invoice_id' => 4, 'item_id' => 2425, 'item_name' => 'System Rain LS25 Shower Column Ø25 mm column, 5F handshower', 'unit_id' => 1, 'quantity' => 312, 'unit_price' => 650, 'vat' => 5, 'vat_amount' => 10140.0, 'discount' => 0, 'line_total' => 202800.0, 'is_transfer' => 0, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 202800.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 464550.0, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 11, 'proforma_invoice_id' => 4, 'item_id' => 8305, 'item_name' => 'Paper Holder, Chrome, 119x44x167 mm', 'unit_id' => 1, 'quantity' => 315, 'unit_price' => 40, 'vat' => 5, 'vat_amount' => 630.0, 'discount' => 0, 'line_total' => 12600.0, 'is_transfer' => 0, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 12600.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 477150.0, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 12, 'proforma_invoice_id' => 4, 'item_id' => 8304, 'item_name' => 'Towel Bar, 60cm', 'unit_id' => 1, 'quantity' => 315, 'unit_price' => 40, 'vat' => 5, 'vat_amount' => 630.0, 'discount' => 0, 'line_total' => 12600.0, 'is_transfer' => 0, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 12600.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 489750.0, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 13, 'proforma_invoice_id' => 4, 'item_id' => 2207, 'item_name' => 'Flo S Sink Mixer', 'unit_id' => 1, 'quantity' => 310, 'unit_price' => 220, 'vat' => 5, 'vat_amount' => 3410.0, 'discount' => 0, 'line_total' => 68200.0, 'is_transfer' => 1, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 68200.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 557950.0, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 14, 'proforma_invoice_id' => 4, 'item_id' => 2990, 'item_name' => 'Minimax Bathrobe Holder - Single', 'unit_id' => 1, 'quantity' => 315, 'unit_price' => 27, 'vat' => 5, 'vat_amount' => 425.25, 'discount' => 0, 'line_total' => 8505.0, 'is_transfer' => 0, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 8505.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 566455.0, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 15, 'proforma_invoice_id' => 4, 'item_id' => 8515, 'item_name' => 'S20 Undercounter Basin, 48 cm, Without tap hole, with overflow hole, 480x300 mm', 'unit_id' => 1, 'quantity' => 312, 'unit_price' => 125, 'vat' => 5, 'vat_amount' => 1950.0, 'discount' => 0, 'line_total' => 39000.0, 'is_transfer' => 0, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 39000.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 605455.0, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 16, 'proforma_invoice_id' => 5, 'item_id' => 9557, 'item_name' => 'Rapid Installation - 3/6 Liter Concealed Cistern Set (Pre-Wall Gypsumplate Wall) - 8 cm - Assembly to wall', 'unit_id' => 1, 'quantity' => 310, 'unit_price' => 445, 'vat' => 5, 'vat_amount' => 6897.5, 'discount' => 0, 'line_total' => 137950.0, 'is_transfer' => 2, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 220, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 137950.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 137950.0, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 17, 'proforma_invoice_id' => 5, 'item_id' => 1624, 'item_name' => 'Loop O Control Panel-Chrome Plated', 'unit_id' => 1, 'quantity' => 310, 'unit_price' => 62, 'vat' => 5, 'vat_amount' => 961.0, 'discount' => 0, 'line_total' => 19220.0, 'is_transfer' => 0, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 19220.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 157170.0, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 18, 'proforma_invoice_id' => 6, 'item_id' => 2389, 'item_name' => 'Bidet Handshower, Plastic, G 3/8”- G 1/2” connector included', 'unit_id' => 1, 'quantity' => 50, 'unit_price' => 65, 'vat' => 5, 'vat_amount' => 162.5, 'discount' => 0, 'line_total' => 3250.0, 'is_transfer' => 2, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 20, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 3250.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 3250.0, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 19, 'proforma_invoice_id' => 6, 'item_id' => 2272, 'item_name' => 'Solid S Basin Mixer  (With Pop-Up), Chrome', 'unit_id' => 1, 'quantity' => 25, 'unit_price' => 154.56, 'vat' => 5, 'vat_amount' => 193.2, 'discount' => 0, 'line_total' => 3864.0, 'is_transfer' => 1, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 3864.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 3864.0, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 20, 'proforma_invoice_id' => 6, 'item_id' => 2258, 'item_name' => 'Fold S Sink Mixer (With Swivel Aerator)', 'unit_id' => 1, 'quantity' => 5, 'unit_price' => 150, 'vat' => 5, 'vat_amount' => 37.5, 'discount' => 0, 'line_total' => 750.0, 'is_transfer' => 1, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 750.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 750.0, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 21, 'proforma_invoice_id' => 7, 'item_id' => 147, 'item_name' => 'Plural White, WC seat, Duroplast, Soft Closing, Gold colored detachable metal hinge, top fixing, quick release', 'unit_id' => 1, 'quantity' => 2, 'unit_price' => 489.44, 'vat' => 5, 'vat_amount' => 48.94, 'discount' => 0, 'line_total' => 978.88, 'is_transfer' => 0, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 978.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 978.88, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 22, 'proforma_invoice_id' => 7, 'item_id' => 1017, 'item_name' => 'D-Light WC-Seat (soft-closing, quick release) ', 'unit_id' => 1, 'quantity' => 1, 'unit_price' => 182.56, 'vat' => 5, 'vat_amount' => 9.13, 'discount' => 0, 'line_total' => 182.56, 'is_transfer' => 0, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 182.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 1161.44, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 23, 'proforma_invoice_id' => 7, 'item_id' => 796, 'item_name' => 'Sento Slim WC Seat, Soft Closing, Quick Release, Matte Taupe', 'unit_id' => 1, 'quantity' => 5, 'unit_price' => 332.64, 'vat' => 5, 'vat_amount' => 83.16, 'discount' => 0, 'line_total' => 1663.2, 'is_transfer' => 0, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 1663.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 2824.64, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 24, 'proforma_invoice_id' => 7, 'item_id' => 1186, 'item_name' => 'S20 WC Seat, PP,,detechable plastic hinge, top fixing', 'unit_id' => 1, 'quantity' => 1, 'unit_price' => 70.56, 'vat' => 5, 'vat_amount' => 3.53, 'discount' => 0, 'line_total' => 70.56, 'is_transfer' => 0, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 70.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 2895.2, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 25, 'proforma_invoice_id' => 7, 'item_id' => 327, 'item_name' => 'Water Jewels Undercounter installation kit for bowls', 'unit_id' => 1, 'quantity' => 2, 'unit_price' => 45.92, 'vat' => 5, 'vat_amount' => 4.59, 'discount' => 0, 'line_total' => 91.84, 'is_transfer' => 0, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 91.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 2987.04, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 26, 'proforma_invoice_id' => 7, 'item_id' => 1460, 'item_name' => 'Electronic Concealed Flusher Shiny Chrome (Mains) (1L)', 'unit_id' => 1, 'quantity' => 2, 'unit_price' => 851.2, 'vat' => 5, 'vat_amount' => 85.12, 'discount' => 0, 'line_total' => 1702.4, 'is_transfer' => 0, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 1702.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 4689.44, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 27, 'proforma_invoice_id' => 7, 'item_id' => 6261, 'item_name' => '80 cm, thermoform, mocha oak wood, side panel', 'unit_id' => 1, 'quantity' => 5, 'unit_price' => 379.68, 'vat' => 5, 'vat_amount' => 94.92, 'discount' => 0, 'line_total' => 1898.4, 'is_transfer' => 0, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 1898.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 6587.84, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 28, 'proforma_invoice_id' => 7, 'item_id' => 6331, 'item_name' => '75 cm Thermoform Patterned Black Oak Wood Side Panel', 'unit_id' => 1, 'quantity' => 3, 'unit_price' => 379.68, 'vat' => 5, 'vat_amount' => 56.95, 'discount' => 0, 'line_total' => 1139.04, 'is_transfer' => 0, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 1139.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 7726.88, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 29, 'proforma_invoice_id' => 7, 'item_id' => 5901, 'item_name' => '90 cm, Wooden Side Panel, Anthracite High Gloss', 'unit_id' => 1, 'quantity' => 1, 'unit_price' => 502.88, 'vat' => 5, 'vat_amount' => 25.14, 'discount' => 0, 'line_total' => 502.88, 'is_transfer' => 0, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 502.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 8229.76, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 30, 'proforma_invoice_id' => 7, 'item_id' => 3049, 'item_name' => 'Arkitekta Cosmetic & Shaving Mirror', 'unit_id' => 1, 'quantity' => 2, 'unit_price' => 403.2, 'vat' => 5, 'vat_amount' => 40.32, 'discount' => 0, 'line_total' => 806.4, 'is_transfer' => 0, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 806.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 9036.16, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 31, 'proforma_invoice_id' => 8, 'item_id' => 2272, 'item_name' => 'Solid S Basin Mixer  (With Pop-Up), Chrome', 'unit_id' => 1, 'quantity' => 100, 'unit_price' => 154.56, 'vat' => 5, 'vat_amount' => 772.8, 'discount' => 0, 'line_total' => 15456.0, 'is_transfer' => 2, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 30, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 15456.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 15456.0, 'pay_pcntg_desc' => '', 'orderno' => 1],
                ['id' => 32, 'proforma_invoice_id' => 8, 'item_id' => 2279, 'item_name' => 'Solid S Shower Mixer', 'unit_id' => 1, 'quantity' => 50, 'unit_price' => 197.12, 'vat' => 5, 'vat_amount' => 492.8, 'discount' => 0, 'line_total' => 9856.0, 'is_transfer' => 2, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 25, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 9856.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 9856.0, 'pay_pcntg_desc' => '', 'orderno' => 2],
                ['id' => 33, 'proforma_invoice_id' => 8, 'item_id' => 972, 'item_name' => 'Integra Wall-hung WC Pan hidden fixation, 54 cm', 'unit_id' => 1, 'quantity' => 50, 'unit_price' => 448, 'vat' => 5, 'vat_amount' => 1120.0, 'discount' => 0, 'line_total' => 22400.0, 'is_transfer' => 1, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 22400.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 22400.0, 'pay_pcntg_desc' => '', 'orderno' => 3],
                ['id' => 34, 'proforma_invoice_id' => 8, 'item_id' => 983, 'item_name' => 'Universal Slim WC Seat & Cover (Duroplast, Soft-Closing)', 'unit_id' => 1, 'quantity' => 50, 'unit_price' => 154.56, 'vat' => 5, 'vat_amount' => 386.4, 'discount' => 0, 'line_total' => 7728.0, 'is_transfer' => 2, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 10, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 7728.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 7728.0, 'pay_pcntg_desc' => '', 'orderno' => 4],
                ['id' => 35, 'proforma_invoice_id' => 9, 'item_id' => 1460, 'item_name' => 'Electronic Concealed Flusher Shiny Chrome (Mains) (1L)', 'unit_id' => 1, 'quantity' => 1, 'unit_price' => 851.2, 'vat' => 5, 'vat_amount' => 42.56, 'discount' => 0, 'line_total' => 851.2, 'is_transfer' => 1, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 851.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 851.2, 'pay_pcntg_desc' => '', 'orderno' => 0],
                ['id' => 36, 'proforma_invoice_id' => 10, 'item_id' => 10757, 'item_name' => 'BS204-M Anima Single wash basin for wall mounting, stainless steel, surface satin finished, material thickness 1 mm, seamless welded bowl with diameter 500 x 335 x 155 mm, oval shape, 90 mm tap ledge, prewelded mounting brackets, with soap dish, includes screws and dowels. Without overflow, 1 1/4\\" flat perforated waste', 'unit_id' => 1, 'quantity' => 1, 'unit_price' => 3020, 'vat' => 5, 'vat_amount' => 151.0, 'discount' => 0, 'line_total' => 3020.0, 'is_transfer' => 0, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 3020.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 3020.0, 'pay_pcntg_desc' => '', 'orderno' => 1],
                ['id' => 37, 'proforma_invoice_id' => 10, 'item_id' => 9218, 'item_name' => 'Acc Fixing for Urinal Jim', 'unit_id' => 1, 'quantity' => 2, 'unit_price' => 41.73, 'vat' => 5, 'vat_amount' => 4.17, 'discount' => 0, 'line_total' => 83.46, 'is_transfer' => 0, 'status' => 1, 'deleted_at' => null, 'balance_quantity' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 83.0, 'item_type' => 0, 'pay_pcntg' => 100, 'pay_amount' => 3103.46, 'pay_pcntg_desc' => '', 'orderno' => 3],
        ]);
    }
}
