<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PurchasesplitReturnItemSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('purchasesplit_return_item')->insert([
                ['id' => 5, 'purchasesplit_return_id' => 4, 'account_id' => 2753, 'item_description' => 'TEL. EXP', 'unit_id' => 'NOS', 'quantity' => 1, 'unit_price' => 5.0, 'vat' => 5, 'item_vat' => 0.25, 'item_jobid' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 5.0, 'unit_price_fc' => 5.0, 'item_vat_fc' => 0.25, 'line_total' => 5.0, 'line_total_fc' => 5.0, 'item_total_fc' => 5.0, 'status' => 1, 'deleted_at' => null, 'item_supname' => '', 'item_vatno' => '', 'purchase_split_return_id' => 4],
                ['id' => 6, 'purchasesplit_return_id' => 4, 'account_id' => 2762, 'item_description' => 'CASH', 'unit_id' => 'NOS', 'quantity' => 1, 'unit_price' => 5.0, 'vat' => 5, 'item_vat' => 0.25, 'item_jobid' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 5.0, 'unit_price_fc' => 5.0, 'item_vat_fc' => 0.25, 'line_total' => 5.0, 'line_total_fc' => 5.0, 'item_total_fc' => 5.0, 'status' => 1, 'deleted_at' => null, 'item_supname' => '', 'item_vatno' => '', 'purchase_split_return_id' => 4],
                ['id' => 7, 'purchasesplit_return_id' => 5, 'account_id' => 2753, 'item_description' => 'TEL. EXP', 'unit_id' => 'NOS', 'quantity' => 1, 'unit_price' => 5.0, 'vat' => 5, 'item_vat' => 0, 'item_jobid' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 5.0, 'unit_price_fc' => 5.0, 'item_vat_fc' => 0.25, 'line_total' => 5.0, 'line_total_fc' => 5.0, 'item_total_fc' => 5.0, 'status' => 1, 'deleted_at' => null, 'item_supname' => '', 'item_vatno' => '', 'purchase_split_return_id' => 5],
                ['id' => 8, 'purchasesplit_return_id' => 5, 'account_id' => 2762, 'item_description' => 'CASH', 'unit_id' => 'NOS', 'quantity' => 1, 'unit_price' => 5.0, 'vat' => 5, 'item_vat' => 0, 'item_jobid' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 5.0, 'unit_price_fc' => 5.0, 'item_vat_fc' => 0.25, 'line_total' => 5.0, 'line_total_fc' => 5.0, 'item_total_fc' => 5.0, 'status' => 1, 'deleted_at' => null, 'item_supname' => '', 'item_vatno' => '', 'purchase_split_return_id' => 5],
                ['id' => 9, 'purchasesplit_return_id' => 6, 'account_id' => 2753, 'item_description' => 'TEL. EXP', 'unit_id' => 'NOS', 'quantity' => 1, 'unit_price' => 5.0, 'vat' => 5, 'item_vat' => 0, 'item_jobid' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 5.0, 'unit_price_fc' => 5.0, 'item_vat_fc' => 0.25, 'line_total' => 5.0, 'line_total_fc' => 5.0, 'item_total_fc' => 5.0, 'status' => 1, 'deleted_at' => null, 'item_supname' => '', 'item_vatno' => '', 'purchase_split_return_id' => 6],
                ['id' => 10, 'purchasesplit_return_id' => 6, 'account_id' => 2762, 'item_description' => 'CASH', 'unit_id' => 'NOS', 'quantity' => 1, 'unit_price' => 5.0, 'vat' => 5, 'item_vat' => 0, 'item_jobid' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 5.0, 'unit_price_fc' => 5.0, 'item_vat_fc' => 0.25, 'line_total' => 5.0, 'line_total_fc' => 5.0, 'item_total_fc' => 5.0, 'status' => 1, 'deleted_at' => null, 'item_supname' => '', 'item_vatno' => '', 'purchase_split_return_id' => 6],
                ['id' => 11, 'purchasesplit_return_id' => 7, 'account_id' => 2753, 'item_description' => 'TEL. EXP', 'unit_id' => 'NOS', 'quantity' => 1, 'unit_price' => 5.0, 'vat' => 5, 'item_vat' => 0.25, 'item_jobid' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 5.0, 'unit_price_fc' => 5.0, 'item_vat_fc' => 0.25, 'line_total' => 5.0, 'line_total_fc' => 5.0, 'item_total_fc' => 5.0, 'status' => 1, 'deleted_at' => null, 'item_supname' => '', 'item_vatno' => '', 'purchase_split_return_id' => 7],
                ['id' => 12, 'purchasesplit_return_id' => 7, 'account_id' => 2762, 'item_description' => 'CASH', 'unit_id' => 'NOS', 'quantity' => 1, 'unit_price' => 5.0, 'vat' => 5, 'item_vat' => 0.25, 'item_jobid' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 5.0, 'unit_price_fc' => 5.0, 'item_vat_fc' => 0.25, 'line_total' => 5.0, 'line_total_fc' => 5.0, 'item_total_fc' => 5.0, 'status' => 1, 'deleted_at' => null, 'item_supname' => '', 'item_vatno' => '', 'purchase_split_return_id' => 7],
                ['id' => 13, 'purchasesplit_return_id' => 8, 'account_id' => 2753, 'item_description' => 'TEL. EXP', 'unit_id' => 'NOS', 'quantity' => 1, 'unit_price' => 5.0, 'vat' => 5, 'item_vat' => 0.25, 'item_jobid' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 5.0, 'unit_price_fc' => 5.0, 'item_vat_fc' => 0.25, 'line_total' => 5.0, 'line_total_fc' => 5.0, 'item_total_fc' => 5.0, 'status' => 1, 'deleted_at' => null, 'item_supname' => '', 'item_vatno' => '', 'purchase_split_return_id' => 8],
                ['id' => 14, 'purchasesplit_return_id' => 8, 'account_id' => 2762, 'item_description' => 'CASH', 'unit_id' => 'NOS', 'quantity' => 1, 'unit_price' => 5.0, 'vat' => 5, 'item_vat' => 0.25, 'item_jobid' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 5.0, 'unit_price_fc' => 5.0, 'item_vat_fc' => 0.25, 'line_total' => 5.0, 'line_total_fc' => 5.0, 'item_total_fc' => 5.0, 'status' => 1, 'deleted_at' => null, 'item_supname' => '', 'item_vatno' => '', 'purchase_split_return_id' => 8],
                ['id' => 15, 'purchasesplit_return_id' => 9, 'account_id' => 2753, 'item_description' => 'TEL. EXP', 'unit_id' => 'NOS', 'quantity' => 1, 'unit_price' => 5.0, 'vat' => 5, 'item_vat' => 0.25, 'item_jobid' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 5.0, 'unit_price_fc' => 5.0, 'item_vat_fc' => 0.25, 'line_total' => 5.0, 'line_total_fc' => 5.0, 'item_total_fc' => 5.0, 'status' => 1, 'deleted_at' => null, 'item_supname' => '', 'item_vatno' => '', 'purchase_split_return_id' => 9],
                ['id' => 16, 'purchasesplit_return_id' => 9, 'account_id' => 2762, 'item_description' => 'CASH', 'unit_id' => 'NOS', 'quantity' => 1, 'unit_price' => 5.0, 'vat' => 5, 'item_vat' => 0.25, 'item_jobid' => 0, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 5.0, 'unit_price_fc' => 5.0, 'item_vat_fc' => 0.25, 'line_total' => 5.0, 'line_total_fc' => 5.0, 'item_total_fc' => 5.0, 'status' => 1, 'deleted_at' => null, 'item_supname' => '', 'item_vatno' => '', 'purchase_split_return_id' => 9],
                ['id' => 17, 'purchasesplit_return_id' => 10, 'account_id' => 5959, 'item_description' => 'Handling Charges(Expenses)', 'unit_id' => 'NOS', 'quantity' => 1, 'unit_price' => 120.0, 'vat' => 5, 'item_vat' => 6, 'item_jobid' => 200, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 120.0, 'unit_price_fc' => 120.0, 'item_vat_fc' => 6.0, 'line_total' => 120.0, 'line_total_fc' => 120.0, 'item_total_fc' => 120.0, 'status' => 1, 'deleted_at' => null, 'item_supname' => '', 'item_vatno' => '', 'purchase_split_return_id' => 10],
                ['id' => 18, 'purchasesplit_return_id' => 11, 'account_id' => 5958, 'item_description' => 'Debit Note', 'unit_id' => 'NOS', 'quantity' => 1, 'unit_price' => 250.0, 'vat' => 5, 'item_vat' => 0, 'item_jobid' => 201, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 250.0, 'unit_price_fc' => 250.0, 'item_vat_fc' => 12.5, 'line_total' => 250.0, 'line_total_fc' => 250.0, 'item_total_fc' => 250.0, 'status' => 1, 'deleted_at' => null, 'item_supname' => '', 'item_vatno' => '', 'purchase_split_return_id' => 11],
                ['id' => 19, 'purchasesplit_return_id' => 12, 'account_id' => 5755, 'item_description' => 'TILE WORK', 'unit_id' => 'NOS', 'quantity' => 1, 'unit_price' => 50.0, 'vat' => 5, 'item_vat' => 2.5, 'item_jobid' => 196, 'tax_code' => 'SR', 'tax_include' => 0, 'item_total' => 50.0, 'unit_price_fc' => 50.0, 'item_vat_fc' => 2.5, 'line_total' => 50.0, 'line_total_fc' => 50.0, 'item_total_fc' => 50.0, 'status' => 1, 'deleted_at' => null, 'item_supname' => '', 'item_vatno' => '', 'purchase_split_return_id' => 12],
        ]);
    }
}
